"""Generated by tools/generate.py — do not edit."""

from __future__ import annotations

from clappform.services.demo import DemoAPI

API_FAMILIES: dict[str, type] = {
    "demo": DemoAPI,
}

__all__ = ["API_FAMILIES", "DemoAPI"]
