"""Generated by tools/generate.py. Do not edit."""

from __future__ import annotations

from collections.abc import Iterable, Iterator, Mapping, Sequence
from typing import Any

from clappform import _runtime
import clappform.gen.clappform.demo.v1.parts.gadget_pb2 as _m_clappform_demo_v1_parts_gadget
import clappform.gen.clappform.demo.v1.parts.widget_pb2 as _m_clappform_demo_v1_parts_widget
import clappform.gen.clappform.demo.v1.thing.thing_pb2 as _m_clappform_demo_v1_thing_thing
import clappform.gen.clappform.v1.commons.commons_pb2 as _m_clappform_v1_commons_commons


class Global(_runtime.ServiceBase):
    """Wrapper for clappform.demo.v1.misc.Global."""

    def pass_(
        self,
        request: _m_clappform_v1_commons_commons.Empty | None = None,
        *,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_v1_commons_commons.Empty:
        """Check liveness.

        RPC: /clappform.demo.v1.misc.Global/Pass (unary-unary)
        """
        _provided: dict[str, Any] = {}
        _request = _runtime.build_request(_m_clappform_v1_commons_commons.Empty, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.demo.v1.misc.Global/Pass",
            _request,
            _m_clappform_v1_commons_commons.Empty,
            _m_clappform_v1_commons_commons.Empty,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )


class ThingManagement(_runtime.ServiceBase):
    """Wrapper for clappform.demo.v1.thing.ThingManagement."""

    def get(
        self,
        request: _m_clappform_v1_commons_commons.Read | None = None,
        *,
        id: str | None = None,
        detail_level: int | None = None,
        include_deleted: bool | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_demo_v1_thing_thing.Thing:
        """Fetch a single thing by id.

        RPC: /clappform.demo.v1.thing.ThingManagement/Get (unary-unary)
        """
        _provided = {_k: _v for _k, _v in (("id", id), ("detail_level", detail_level), ("include_deleted", include_deleted),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_v1_commons_commons.Read, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.demo.v1.thing.ThingManagement/Get",
            _request,
            _m_clappform_v1_commons_commons.Read,
            _m_clappform_demo_v1_thing_thing.Thing,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def get_all(
        self,
        request: _m_clappform_v1_commons_commons.PaginationRequest | None = None,
        *,
        page: int | None = None,
        limit: int | None = None,
        sort: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_demo_v1_thing_thing.Things:
        """List things with pagination.

        RPC: /clappform.demo.v1.thing.ThingManagement/GetAll (unary-unary)
        """
        _provided = {_k: _v for _k, _v in (("page", page), ("limit", limit), ("sort", sort),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_v1_commons_commons.PaginationRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.demo.v1.thing.ThingManagement/GetAll",
            _request,
            _m_clappform_v1_commons_commons.PaginationRequest,
            _m_clappform_demo_v1_thing_thing.Things,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def iter_get_all(
        self,
        *,
        limit: int | None = None,
        sort: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> Iterator[_m_clappform_demo_v1_thing_thing.Thing]:
        """Auto-paginating variant of ``get_all``.

        Yields each item from ``things``, requesting page 1, 2, ... until
        a page comes back empty or ``pagination.pages`` is reached.
        """
        _page = 1
        while True:
            _resp = self.get_all(page=_page, limit=limit, sort=sort, timeout=timeout, metadata=metadata, location=location)
            _items = _resp.things
            yield from _items
            if not _items or _resp.pagination.pages <= _page:
                break
            _page += 1

    def upload(
        self,
        requests: Iterable[_m_clappform_demo_v1_thing_thing.UploadRequest],
        *,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_demo_v1_thing_thing.UploadSummary:
        """Upload things in bulk.

        RPC: /clappform.demo.v1.thing.ThingManagement/Upload (stream-unary)
        """
        _requests = _runtime.ensure_iterable(requests, _m_clappform_demo_v1_thing_thing.UploadRequest)
        return self._caller.invoke(
            "stream_unary",
            "/clappform.demo.v1.thing.ThingManagement/Upload",
            _requests,
            _m_clappform_demo_v1_thing_thing.UploadRequest,
            _m_clappform_demo_v1_thing_thing.UploadSummary,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def watch(
        self,
        request: _m_clappform_v1_commons_commons.Read | None = None,
        *,
        id: str | None = None,
        detail_level: int | None = None,
        include_deleted: bool | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> Iterator[_m_clappform_demo_v1_thing_thing.Thing]:
        """Watch things as they change.

        RPC: /clappform.demo.v1.thing.ThingManagement/Watch (unary-stream)
        """
        _provided = {_k: _v for _k, _v in (("id", id), ("detail_level", detail_level), ("include_deleted", include_deleted),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_v1_commons_commons.Read, request, _provided)
        return self._caller.invoke(
            "unary_stream",
            "/clappform.demo.v1.thing.ThingManagement/Watch",
            _request,
            _m_clappform_v1_commons_commons.Read,
            _m_clappform_demo_v1_thing_thing.Thing,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def exchange(
        self,
        requests: Iterable[_m_clappform_demo_v1_thing_thing.UploadRequest],
        *,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> Iterator[_m_clappform_demo_v1_thing_thing.Thing]:
        """RPC: /clappform.demo.v1.thing.ThingManagement/Exchange (stream-stream)"""
        _requests = _runtime.ensure_iterable(requests, _m_clappform_demo_v1_thing_thing.UploadRequest)
        return self._caller.invoke(
            "stream_stream",
            "/clappform.demo.v1.thing.ThingManagement/Exchange",
            _requests,
            _m_clappform_demo_v1_thing_thing.UploadRequest,
            _m_clappform_demo_v1_thing_thing.Thing,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def collide(
        self,
        request: _m_clappform_demo_v1_thing_thing.CollisionRequest | None = None,
        *,
        location_: str | None = None,
        payload: str | None = None,
        timeout_: int | None = None,
        from_: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_v1_commons_commons.Message:
        """Exercise reserved field names.

        Fields named like a per-call argument or a Python keyword
        get a trailing underscore.

        RPC: /clappform.demo.v1.thing.ThingManagement/Collide (unary-unary)

        Args:
            location_: Collides with the per-call tenant argument.
            timeout_: Server-side task timeout in seconds, unrelated to the gRPC deadline.
            from_: Python keyword.
        """
        _provided = {_k: _v for _k, _v in (("location", location_), ("payload", payload), ("timeout", timeout_), ("from", from_),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_demo_v1_thing_thing.CollisionRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.demo.v1.thing.ThingManagement/Collide",
            _request,
            _m_clappform_demo_v1_thing_thing.CollisionRequest,
            _m_clappform_v1_commons_commons.Message,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def import_(
        self,
        request: _m_clappform_demo_v1_thing_thing.ImportRequest | None = None,
        *,
        source: _m_clappform_demo_v1_thing_thing.Source | int | str | None = None,
        state: _m_clappform_demo_v1_thing_thing.Thing.State | int | str | None = None,
        dimensions: _m_clappform_demo_v1_thing_thing.Thing.Dimensions | Mapping[str, Any] | None = None,
        widgets: dict[str, _m_clappform_demo_v1_parts_widget.Widget | Mapping[str, Any]] | None = None,
        inline: bytes | None = None,
        url: str | None = None,
        fallbacks: Sequence[_m_clappform_demo_v1_thing_thing.Source | int | str] | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_v1_commons_commons.Message:
        """Import things from an external source.

        The RPC name is a Python
        keyword, and this comment wraps over several lines:
          - the first sentence becomes the summary
          - relative indentation survives

        RPC: /clappform.demo.v1.thing.ThingManagement/Import (unary-unary)

        Args:
            source: Where the data comes from.
            state: Initial state of the imported things.
            inline: Raw bytes to import.
            url: Location to fetch from.
                  Must be https.
        """
        _provided = {_k: _v for _k, _v in (("source", source), ("state", state), ("dimensions", dimensions), ("widgets", widgets), ("inline", inline), ("url", url), ("fallbacks", fallbacks),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_demo_v1_thing_thing.ImportRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.demo.v1.thing.ThingManagement/Import",
            _request,
            _m_clappform_demo_v1_thing_thing.ImportRequest,
            _m_clappform_v1_commons_commons.Message,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def list_gadgets(
        self,
        request: _m_clappform_v1_commons_commons.PaginationRequest | None = None,
        *,
        page: int | None = None,
        limit: int | None = None,
        sort: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_demo_v1_thing_thing.Gadgets:
        """List gadgets, whose message lives in another file.

        RPC: /clappform.demo.v1.thing.ThingManagement/ListGadgets (unary-unary)
        """
        _provided = {_k: _v for _k, _v in (("page", page), ("limit", limit), ("sort", sort),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_v1_commons_commons.PaginationRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.demo.v1.thing.ThingManagement/ListGadgets",
            _request,
            _m_clappform_v1_commons_commons.PaginationRequest,
            _m_clappform_demo_v1_thing_thing.Gadgets,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def iter_list_gadgets(
        self,
        *,
        limit: int | None = None,
        sort: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> Iterator[_m_clappform_demo_v1_parts_gadget.Gadget]:
        """Auto-paginating variant of ``list_gadgets``.

        Yields each item from ``gadgets``, requesting page 1, 2, ... until
        a page comes back empty or ``pagination.pages`` is reached.
        """
        _page = 1
        while True:
            _resp = self.list_gadgets(page=_page, limit=limit, sort=sort, timeout=timeout, metadata=metadata, location=location)
            _items = _resp.gadgets
            yield from _items
            if not _items or _resp.pagination.pages <= _page:
                break
            _page += 1

    def list_bundles(
        self,
        request: _m_clappform_v1_commons_commons.PaginationRequest | None = None,
        *,
        page: int | None = None,
        limit: int | None = None,
        sort: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_demo_v1_thing_thing.Bundles:
        """List bundles, a response with more than one repeated message field.

        RPC: /clappform.demo.v1.thing.ThingManagement/ListBundles (unary-unary)
        """
        _provided = {_k: _v for _k, _v in (("page", page), ("limit", limit), ("sort", sort),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_v1_commons_commons.PaginationRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.demo.v1.thing.ThingManagement/ListBundles",
            _request,
            _m_clappform_v1_commons_commons.PaginationRequest,
            _m_clappform_demo_v1_thing_thing.Bundles,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def iter_list_bundles(
        self,
        *,
        limit: int | None = None,
        sort: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> Iterator[_m_clappform_demo_v1_thing_thing.Thing]:
        """Auto-paginating variant of ``list_bundles``.

        Yields each item from ``things``, requesting page 1, 2, ... until
        a page comes back empty or ``pagination.pages`` is reached.
        Only ``things`` is yielded; call ``list_bundles`` for ``summaries``.
        """
        _page = 1
        while True:
            _resp = self.list_bundles(page=_page, limit=limit, sort=sort, timeout=timeout, metadata=metadata, location=location)
            _items = _resp.things
            yield from _items
            if not _items or _resp.pagination.pages <= _page:
                break
            _page += 1

    def send_whatsapp_message(
        self,
        request: _m_clappform_v1_commons_commons.Read | None = None,
        *,
        id: str | None = None,
        detail_level: int | None = None,
        include_deleted: bool | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_v1_commons_commons.Empty:
        """Send a message over WhatsApp.

        RPC: /clappform.demo.v1.thing.ThingManagement/SendWhatsAppMessage (unary-unary)
        """
        _provided = {_k: _v for _k, _v in (("id", id), ("detail_level", detail_level), ("include_deleted", include_deleted),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_v1_commons_commons.Read, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.demo.v1.thing.ThingManagement/SendWhatsAppMessage",
            _request,
            _m_clappform_v1_commons_commons.Read,
            _m_clappform_v1_commons_commons.Empty,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )


class DemoAPI:
    """Generated sub-client for the demo API."""

    def __init__(self, caller: _runtime.Caller) -> None:
        self.global_ = Global(caller)
        self.thing = ThingManagement(caller)
