"""Generated by tools/generate.py. Do not edit."""

from __future__ import annotations

from collections.abc import Iterable, Iterator, Sequence
from typing import Any

from clappform import _runtime
import clappform.gen.clappform.demo.v1.thing.thing_pb2 as _m_clappform_demo_v1_thing_thing
import clappform.gen.clappform.v1.commons.commons_pb2 as _m_clappform_v1_commons_commons


class ThingManagement(_runtime.ServiceBase):
    """Wrapper for clappform.demo.v1.thing.ThingManagement."""

    def get(
        self,
        request: _m_clappform_v1_commons_commons.Read | None = None,
        *,
        id: str | None = None,
        detail_level: int | None = None,
        include_deleted: bool | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_demo_v1_thing_thing.Thing:
        """Fetch a single thing by id.

        RPC: /clappform.demo.v1.thing.ThingManagement/Get (unary-unary)
        """
        _provided = {_k: _v for _k, _v in (("id", id), ("detail_level", detail_level), ("include_deleted", include_deleted),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_v1_commons_commons.Read, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.demo.v1.thing.ThingManagement/Get",
            _request,
            _m_clappform_v1_commons_commons.Read,
            _m_clappform_demo_v1_thing_thing.Thing,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def get_all(
        self,
        request: _m_clappform_v1_commons_commons.PaginationRequest | None = None,
        *,
        page: int | None = None,
        limit: int | None = None,
        sort: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_demo_v1_thing_thing.Things:
        """List things with pagination.

        RPC: /clappform.demo.v1.thing.ThingManagement/GetAll (unary-unary)
        """
        _provided = {_k: _v for _k, _v in (("page", page), ("limit", limit), ("sort", sort),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_v1_commons_commons.PaginationRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.demo.v1.thing.ThingManagement/GetAll",
            _request,
            _m_clappform_v1_commons_commons.PaginationRequest,
            _m_clappform_demo_v1_thing_thing.Things,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def iter_get_all(
        self,
        *,
        limit: int | None = None,
        sort: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> Iterator[_m_clappform_demo_v1_thing_thing.Thing]:
        """Auto-paginating variant of ``get_all``.

        Yields each item from ``things`` across all pages, following
        ``pagination`` until the last page.
        """
        _page = 1
        while True:
            _resp = self.get_all(page=_page, limit=limit, sort=sort, timeout=timeout, metadata=metadata, location=location)
            yield from _resp.things
            _pagination = _resp.pagination
            if _pagination.pages <= _pagination.page:
                break
            _page = _pagination.page + 1

    def upload(
        self,
        requests: Iterable[_m_clappform_demo_v1_thing_thing.UploadRequest],
        *,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_demo_v1_thing_thing.UploadSummary:
        """Upload things in bulk.

        RPC: /clappform.demo.v1.thing.ThingManagement/Upload (stream-unary)
        """
        _requests = _runtime.ensure_iterable(requests, _m_clappform_demo_v1_thing_thing.UploadRequest)
        return self._caller.invoke(
            "stream_unary",
            "/clappform.demo.v1.thing.ThingManagement/Upload",
            _requests,
            _m_clappform_demo_v1_thing_thing.UploadRequest,
            _m_clappform_demo_v1_thing_thing.UploadSummary,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def watch(
        self,
        request: _m_clappform_v1_commons_commons.Read | None = None,
        *,
        id: str | None = None,
        detail_level: int | None = None,
        include_deleted: bool | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> Iterator[_m_clappform_demo_v1_thing_thing.Thing]:
        """Watch things as they change.

        RPC: /clappform.demo.v1.thing.ThingManagement/Watch (unary-stream)
        """
        _provided = {_k: _v for _k, _v in (("id", id), ("detail_level", detail_level), ("include_deleted", include_deleted),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_v1_commons_commons.Read, request, _provided)
        return self._caller.invoke(
            "unary_stream",
            "/clappform.demo.v1.thing.ThingManagement/Watch",
            _request,
            _m_clappform_v1_commons_commons.Read,
            _m_clappform_demo_v1_thing_thing.Thing,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def exchange(
        self,
        requests: Iterable[_m_clappform_demo_v1_thing_thing.UploadRequest],
        *,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> Iterator[_m_clappform_demo_v1_thing_thing.Thing]:
        """RPC: /clappform.demo.v1.thing.ThingManagement/Exchange (stream-stream)"""
        _requests = _runtime.ensure_iterable(requests, _m_clappform_demo_v1_thing_thing.UploadRequest)
        return self._caller.invoke(
            "stream_stream",
            "/clappform.demo.v1.thing.ThingManagement/Exchange",
            _requests,
            _m_clappform_demo_v1_thing_thing.UploadRequest,
            _m_clappform_demo_v1_thing_thing.Thing,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def collide(
        self,
        request: _m_clappform_demo_v1_thing_thing.CollisionRequest | None = None,
        *,
        payload: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_v1_commons_commons.Message:
        """RPC: /clappform.demo.v1.thing.ThingManagement/Collide (unary-unary)
        Fields only settable via a request message (name collision): location
        """
        _provided = {_k: _v for _k, _v in (("payload", payload),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_demo_v1_thing_thing.CollisionRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.demo.v1.thing.ThingManagement/Collide",
            _request,
            _m_clappform_demo_v1_thing_thing.CollisionRequest,
            _m_clappform_v1_commons_commons.Message,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )


class DemoAPI:
    """Generated sub-client for the demo API."""

    def __init__(self, caller: _runtime.Caller) -> None:
        self.thing = ThingManagement(caller)
