"""Generated by tools/generate.py — do not edit."""

from __future__ import annotations

from clappform.services.auth import AuthAPI
from clappform.services.client import ClientAPI
from clappform.services.data import DataAPI
from clappform.services.notifier import NotifierAPI

API_FAMILIES: dict[str, type] = {
    "auth": AuthAPI,
    "client": ClientAPI,
    "data": DataAPI,
    "notifier": NotifierAPI,
}

__all__ = ["API_FAMILIES", "AuthAPI", "ClientAPI", "DataAPI", "NotifierAPI"]
