"""Generated by tools/generate.py. Do not edit."""

from __future__ import annotations

from collections.abc import Iterable, Iterator, Sequence
from typing import Any

from clappform import _runtime
import clappform.gen.clappform.authoriser.v1.apikey.apikey_pb2 as _m_clappform_authoriser_v1_apikey_apikey
import clappform.gen.clappform.authoriser.v1.azure.azure_pb2 as _m_clappform_authoriser_v1_azure_azure
import clappform.gen.clappform.authoriser.v1.guestkey.guestkey_pb2 as _m_clappform_authoriser_v1_guestkey_guestkey
import clappform.gen.clappform.authoriser.v1.otp.otp_pb2 as _m_clappform_authoriser_v1_otp_otp
import clappform.gen.clappform.authoriser.v1.password.password_pb2 as _m_clappform_authoriser_v1_password_password
import clappform.gen.clappform.authoriser.v1.permission.permission_pb2 as _m_clappform_authoriser_v1_permission_permission
import clappform.gen.clappform.authoriser.v1.recover.recover_pb2 as _m_clappform_authoriser_v1_recover_recover
import clappform.gen.clappform.authoriser.v1.role.role_pb2 as _m_clappform_authoriser_v1_role_role
import clappform.gen.clappform.authoriser.v1.security_profile.security_profile_pb2 as _m_clappform_authoriser_v1_security_profile_security_profile
import clappform.gen.clappform.authoriser.v1.user.user_pb2 as _m_clappform_authoriser_v1_user_user
import clappform.gen.clappform.authoriser.v1.version.version_pb2 as _m_clappform_authoriser_v1_version_version
import clappform.gen.clappform.v1.commons.commons_pb2 as _m_clappform_v1_commons_commons


class APIKeyManagement(_runtime.ServiceBase):
    """Wrapper for clappform.authoriser.v1.apikey.APIKeyManagement."""

    def read_all(
        self,
        request: _m_clappform_v1_commons_commons.PaginationRequest | None = None,
        *,
        page: int | None = None,
        limit: int | None = None,
        batch_size: int | None = None,
        query_parameters: str | None = None,
        include_deleted: bool | None = None,
        detail_level: int | None = None,
        sort: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_authoriser_v1_apikey_apikey.APIKeys:
        """RPC: /clappform.authoriser.v1.apikey.APIKeyManagement/ReadAll (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("page", page), ("limit", limit), ("batch_size", batch_size), ("query_parameters", query_parameters), ("include_deleted", include_deleted), ("detail_level", detail_level), ("sort", sort),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_v1_commons_commons.PaginationRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.authoriser.v1.apikey.APIKeyManagement/ReadAll",
            _request,
            _m_clappform_v1_commons_commons.PaginationRequest,
            _m_clappform_authoriser_v1_apikey_apikey.APIKeys,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def iter_read_all(
        self,
        *,
        limit: int | None = None,
        batch_size: int | None = None,
        query_parameters: str | None = None,
        include_deleted: bool | None = None,
        detail_level: int | None = None,
        sort: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> Iterator[_m_clappform_authoriser_v1_apikey_apikey.APIKey]:
        """Auto-paginating variant of ``read_all``.

        Yields each item from ``api_keys`` across all pages, following
        ``pagination`` until the last page.
        """
        _page = 1
        while True:
            _resp = self.read_all(page=_page, limit=limit, batch_size=batch_size, query_parameters=query_parameters, include_deleted=include_deleted, detail_level=detail_level, sort=sort, timeout=timeout, metadata=metadata, location=location)
            yield from _resp.api_keys
            _pagination = _resp.pagination
            if _pagination.pages <= _pagination.page:
                break
            _page = _pagination.page + 1

    def generate_key(
        self,
        request: _m_clappform_authoriser_v1_apikey_apikey.GenerateKeyRequest | None = None,
        *,
        name: str | None = None,
        expiration_date: int | None = None,
        permissions: Sequence[_m_clappform_authoriser_v1_permission_permission.Permission] | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_authoriser_v1_apikey_apikey.APIKey:
        """RPC: /clappform.authoriser.v1.apikey.APIKeyManagement/GenerateKey (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("name", name), ("expiration_date", expiration_date), ("permissions", permissions),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_authoriser_v1_apikey_apikey.GenerateKeyRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.authoriser.v1.apikey.APIKeyManagement/GenerateKey",
            _request,
            _m_clappform_authoriser_v1_apikey_apikey.GenerateKeyRequest,
            _m_clappform_authoriser_v1_apikey_apikey.APIKey,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def verify_key(
        self,
        request: _m_clappform_authoriser_v1_apikey_apikey.VerifyKeyRequest | None = None,
        *,
        api_key: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_authoriser_v1_apikey_apikey.VerifyKeyResponse:
        """RPC: /clappform.authoriser.v1.apikey.APIKeyManagement/VerifyKey (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("api_key", api_key),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_authoriser_v1_apikey_apikey.VerifyKeyRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.authoriser.v1.apikey.APIKeyManagement/VerifyKey",
            _request,
            _m_clappform_authoriser_v1_apikey_apikey.VerifyKeyRequest,
            _m_clappform_authoriser_v1_apikey_apikey.VerifyKeyResponse,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def delete_key(
        self,
        request: _m_clappform_v1_commons_commons.Read | None = None,
        *,
        id: str | None = None,
        detail_level: int | None = None,
        include_deleted: bool | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_v1_commons_commons.Message:
        """RPC: /clappform.authoriser.v1.apikey.APIKeyManagement/DeleteKey (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("id", id), ("detail_level", detail_level), ("include_deleted", include_deleted),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_v1_commons_commons.Read, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.authoriser.v1.apikey.APIKeyManagement/DeleteKey",
            _request,
            _m_clappform_v1_commons_commons.Read,
            _m_clappform_v1_commons_commons.Message,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )


class AzureManagement(_runtime.ServiceBase):
    """Wrapper for clappform.authoriser.v1.azure.AzureManagement."""

    def read_all(
        self,
        request: _m_clappform_v1_commons_commons.PaginationRequest | None = None,
        *,
        page: int | None = None,
        limit: int | None = None,
        batch_size: int | None = None,
        query_parameters: str | None = None,
        include_deleted: bool | None = None,
        detail_level: int | None = None,
        sort: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_authoriser_v1_azure_azure.AzureAuthorities:
        """RPC: /clappform.authoriser.v1.azure.AzureManagement/ReadAll (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("page", page), ("limit", limit), ("batch_size", batch_size), ("query_parameters", query_parameters), ("include_deleted", include_deleted), ("detail_level", detail_level), ("sort", sort),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_v1_commons_commons.PaginationRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.authoriser.v1.azure.AzureManagement/ReadAll",
            _request,
            _m_clappform_v1_commons_commons.PaginationRequest,
            _m_clappform_authoriser_v1_azure_azure.AzureAuthorities,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def iter_read_all(
        self,
        *,
        limit: int | None = None,
        batch_size: int | None = None,
        query_parameters: str | None = None,
        include_deleted: bool | None = None,
        detail_level: int | None = None,
        sort: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> Iterator[_m_clappform_authoriser_v1_azure_azure.AzureAuthority]:
        """Auto-paginating variant of ``read_all``.

        Yields each item from ``authorities`` across all pages, following
        ``pagination`` until the last page.
        """
        _page = 1
        while True:
            _resp = self.read_all(page=_page, limit=limit, batch_size=batch_size, query_parameters=query_parameters, include_deleted=include_deleted, detail_level=detail_level, sort=sort, timeout=timeout, metadata=metadata, location=location)
            yield from _resp.authorities
            _pagination = _resp.pagination
            if _pagination.pages <= _pagination.page:
                break
            _page = _pagination.page + 1

    def azure_auth(
        self,
        request: _m_clappform_authoriser_v1_azure_azure.AzureAuthRequest | None = None,
        *,
        authority: str | None = None,
        code_challenge: str | None = None,
        state: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_authoriser_v1_azure_azure.AzureAuthResponse:
        """RPC: /clappform.authoriser.v1.azure.AzureManagement/AzureAuth (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("authority", authority), ("code_challenge", code_challenge), ("state", state),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_authoriser_v1_azure_azure.AzureAuthRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.authoriser.v1.azure.AzureManagement/AzureAuth",
            _request,
            _m_clappform_authoriser_v1_azure_azure.AzureAuthRequest,
            _m_clappform_authoriser_v1_azure_azure.AzureAuthResponse,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def azure_auth_samlacs(
        self,
        request: _m_clappform_authoriser_v1_azure_azure.AzureAuthACSRequest | None = None,
        *,
        SAMLResponse: bytes | None = None,
        authority: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_authoriser_v1_password_password.AuthTokenResponse:
        """RPC: /clappform.authoriser.v1.azure.AzureManagement/AzureAuthSAMLACS (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("SAMLResponse", SAMLResponse), ("authority", authority),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_authoriser_v1_azure_azure.AzureAuthACSRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.authoriser.v1.azure.AzureManagement/AzureAuthSAMLACS",
            _request,
            _m_clappform_authoriser_v1_azure_azure.AzureAuthACSRequest,
            _m_clappform_authoriser_v1_password_password.AuthTokenResponse,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def azure_auth_o_auth_acs(
        self,
        request: _m_clappform_authoriser_v1_azure_azure.AzureAuthOAuthACSRequest | None = None,
        *,
        code: str | None = None,
        authority: str | None = None,
        code_challenge: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_authoriser_v1_password_password.AuthTokenResponse:
        """RPC: /clappform.authoriser.v1.azure.AzureManagement/AzureAuthOAuthACS (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("code", code), ("authority", authority), ("code_challenge", code_challenge),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_authoriser_v1_azure_azure.AzureAuthOAuthACSRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.authoriser.v1.azure.AzureManagement/AzureAuthOAuthACS",
            _request,
            _m_clappform_authoriser_v1_azure_azure.AzureAuthOAuthACSRequest,
            _m_clappform_authoriser_v1_password_password.AuthTokenResponse,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def azure_log_out(
        self,
        request: _m_clappform_authoriser_v1_azure_azure.AzureAuthRequest | None = None,
        *,
        authority: str | None = None,
        code_challenge: str | None = None,
        state: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_authoriser_v1_azure_azure.AzureAuthResponse:
        """RPC: /clappform.authoriser.v1.azure.AzureManagement/AzureLogOut (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("authority", authority), ("code_challenge", code_challenge), ("state", state),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_authoriser_v1_azure_azure.AzureAuthRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.authoriser.v1.azure.AzureManagement/AzureLogOut",
            _request,
            _m_clappform_authoriser_v1_azure_azure.AzureAuthRequest,
            _m_clappform_authoriser_v1_azure_azure.AzureAuthResponse,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )


class GeneralManagement(_runtime.ServiceBase):
    """Wrapper for clappform.authoriser.v1.general.GeneralManagement."""

    def general(
        self,
        request: _m_clappform_v1_commons_commons.Empty | None = None,
        *,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_v1_commons_commons.Message:
        """RPC: /clappform.authoriser.v1.general.GeneralManagement/General (unary-unary)"""
        _provided: dict[str, Any] = {}
        _request = _runtime.build_request(_m_clappform_v1_commons_commons.Empty, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.authoriser.v1.general.GeneralManagement/General",
            _request,
            _m_clappform_v1_commons_commons.Empty,
            _m_clappform_v1_commons_commons.Message,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )


class GuestKeyManagement(_runtime.ServiceBase):
    """Wrapper for clappform.authoriser.v1.guestkey.GuestKeyManagement."""

    def get_public_access_token(
        self,
        request: _m_clappform_v1_commons_commons.Empty | None = None,
        *,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_authoriser_v1_password_password.AuthTokenResponse:
        """RPC: /clappform.authoriser.v1.guestkey.GuestKeyManagement/GetPublicAccessToken (unary-unary)"""
        _provided: dict[str, Any] = {}
        _request = _runtime.build_request(_m_clappform_v1_commons_commons.Empty, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.authoriser.v1.guestkey.GuestKeyManagement/GetPublicAccessToken",
            _request,
            _m_clappform_v1_commons_commons.Empty,
            _m_clappform_authoriser_v1_password_password.AuthTokenResponse,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def get_elevated_access_token(
        self,
        request: _m_clappform_authoriser_v1_guestkey_guestkey.AuthRequest | None = None,
        *,
        deep_dive: bytes | None = None,
        permissions: Sequence[str] | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_authoriser_v1_password_password.AuthTokenResponse:
        """RPC: /clappform.authoriser.v1.guestkey.GuestKeyManagement/GetElevatedAccessToken (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("deep_dive", deep_dive), ("permissions", permissions),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_authoriser_v1_guestkey_guestkey.AuthRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.authoriser.v1.guestkey.GuestKeyManagement/GetElevatedAccessToken",
            _request,
            _m_clappform_authoriser_v1_guestkey_guestkey.AuthRequest,
            _m_clappform_authoriser_v1_password_password.AuthTokenResponse,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def create_base_role(
        self,
        request: _m_clappform_v1_commons_commons.Empty | None = None,
        *,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_v1_commons_commons.Empty:
        """RPC: /clappform.authoriser.v1.guestkey.GuestKeyManagement/CreateBaseRole (unary-unary)"""
        _provided: dict[str, Any] = {}
        _request = _runtime.build_request(_m_clappform_v1_commons_commons.Empty, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.authoriser.v1.guestkey.GuestKeyManagement/CreateBaseRole",
            _request,
            _m_clappform_v1_commons_commons.Empty,
            _m_clappform_v1_commons_commons.Empty,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )


class OtpManagement(_runtime.ServiceBase):
    """Wrapper for clappform.authoriser.v1.otp.OtpManagement."""

    def setup(
        self,
        request: _m_clappform_v1_commons_commons.Empty | None = None,
        *,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_authoriser_v1_otp_otp.GenerateResponse:
        """RPC: /clappform.authoriser.v1.otp.OtpManagement/Setup (unary-unary)"""
        _provided: dict[str, Any] = {}
        _request = _runtime.build_request(_m_clappform_v1_commons_commons.Empty, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.authoriser.v1.otp.OtpManagement/Setup",
            _request,
            _m_clappform_v1_commons_commons.Empty,
            _m_clappform_authoriser_v1_otp_otp.GenerateResponse,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def verify_setup(
        self,
        request: _m_clappform_authoriser_v1_otp_otp.TokenRequest | None = None,
        *,
        token: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_authoriser_v1_otp_otp.VerifyResponse:
        """RPC: /clappform.authoriser.v1.otp.OtpManagement/VerifySetup (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("token", token),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_authoriser_v1_otp_otp.TokenRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.authoriser.v1.otp.OtpManagement/VerifySetup",
            _request,
            _m_clappform_authoriser_v1_otp_otp.TokenRequest,
            _m_clappform_authoriser_v1_otp_otp.VerifyResponse,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def validate(
        self,
        request: _m_clappform_authoriser_v1_otp_otp.ValidateRequest | None = None,
        *,
        input_token: str | None = None,
        validation_key: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_authoriser_v1_otp_otp.ValidateResponse:
        """RPC: /clappform.authoriser.v1.otp.OtpManagement/Validate (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("input_token", input_token), ("validation_key", validation_key),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_authoriser_v1_otp_otp.ValidateRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.authoriser.v1.otp.OtpManagement/Validate",
            _request,
            _m_clappform_authoriser_v1_otp_otp.ValidateRequest,
            _m_clappform_authoriser_v1_otp_otp.ValidateResponse,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def disable(
        self,
        request: _m_clappform_v1_commons_commons.Empty | None = None,
        *,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_v1_commons_commons.Message:
        """RPC: /clappform.authoriser.v1.otp.OtpManagement/Disable (unary-unary)"""
        _provided: dict[str, Any] = {}
        _request = _runtime.build_request(_m_clappform_v1_commons_commons.Empty, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.authoriser.v1.otp.OtpManagement/Disable",
            _request,
            _m_clappform_v1_commons_commons.Empty,
            _m_clappform_v1_commons_commons.Message,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def recover(
        self,
        request: _m_clappform_authoriser_v1_otp_otp.RecoverRequest | None = None,
        *,
        token: str | None = None,
        username: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_authoriser_v1_otp_otp.RecoverResponse:
        """RPC: /clappform.authoriser.v1.otp.OtpManagement/Recover (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("token", token), ("username", username),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_authoriser_v1_otp_otp.RecoverRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.authoriser.v1.otp.OtpManagement/Recover",
            _request,
            _m_clappform_authoriser_v1_otp_otp.RecoverRequest,
            _m_clappform_authoriser_v1_otp_otp.RecoverResponse,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def regenerate_recovery_codes(
        self,
        request: _m_clappform_authoriser_v1_otp_otp.TokenRequest | None = None,
        *,
        token: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_authoriser_v1_otp_otp.RecoveryCodesResponse:
        """RPC: /clappform.authoriser.v1.otp.OtpManagement/RegenerateRecoveryCodes (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("token", token),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_authoriser_v1_otp_otp.TokenRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.authoriser.v1.otp.OtpManagement/RegenerateRecoveryCodes",
            _request,
            _m_clappform_authoriser_v1_otp_otp.TokenRequest,
            _m_clappform_authoriser_v1_otp_otp.RecoveryCodesResponse,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )


class PasswordManagement(_runtime.ServiceBase):
    """Wrapper for clappform.authoriser.v1.password.PasswordManagement."""

    def auth(
        self,
        request: _m_clappform_authoriser_v1_password_password.AuthRequest | None = None,
        *,
        username: str | None = None,
        password: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_authoriser_v1_password_password.AuthTokenResponse:
        """RPC: /clappform.authoriser.v1.password.PasswordManagement/Auth (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("username", username), ("password", password),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_authoriser_v1_password_password.AuthRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.authoriser.v1.password.PasswordManagement/Auth",
            _request,
            _m_clappform_authoriser_v1_password_password.AuthRequest,
            _m_clappform_authoriser_v1_password_password.AuthTokenResponse,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def de_auth(
        self,
        request: _m_clappform_v1_commons_commons.Empty | None = None,
        *,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_authoriser_v1_password_password.DeauthResponse:
        """RPC: /clappform.authoriser.v1.password.PasswordManagement/DeAuth (unary-unary)"""
        _provided: dict[str, Any] = {}
        _request = _runtime.build_request(_m_clappform_v1_commons_commons.Empty, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.authoriser.v1.password.PasswordManagement/DeAuth",
            _request,
            _m_clappform_v1_commons_commons.Empty,
            _m_clappform_authoriser_v1_password_password.DeauthResponse,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def refresh(
        self,
        request: _m_clappform_authoriser_v1_password_password.RefreshTokenRequest | None = None,
        *,
        refresh_token: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_authoriser_v1_password_password.AuthTokenResponse:
        """RPC: /clappform.authoriser.v1.password.PasswordManagement/Refresh (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("refresh_token", refresh_token),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_authoriser_v1_password_password.RefreshTokenRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.authoriser.v1.password.PasswordManagement/Refresh",
            _request,
            _m_clappform_authoriser_v1_password_password.RefreshTokenRequest,
            _m_clappform_authoriser_v1_password_password.AuthTokenResponse,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def verify(
        self,
        request: _m_clappform_authoriser_v1_password_password.AuthTokenRequest | None = None,
        *,
        authorization_token: str | None = None,
        detail_level: int | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_authoriser_v1_password_password.AuthUserResponse:
        """RPC: /clappform.authoriser.v1.password.PasswordManagement/Verify (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("authorization_token", authorization_token), ("detail_level", detail_level),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_authoriser_v1_password_password.AuthTokenRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.authoriser.v1.password.PasswordManagement/Verify",
            _request,
            _m_clappform_authoriser_v1_password_password.AuthTokenRequest,
            _m_clappform_authoriser_v1_password_password.AuthUserResponse,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )


class PermissionManagement(_runtime.ServiceBase):
    """Wrapper for clappform.authoriser.v1.permission.PermissionManagement."""

    def create(
        self,
        request: _m_clappform_authoriser_v1_permission_permission.Permissions | None = None,
        *,
        permissions: Sequence[_m_clappform_authoriser_v1_permission_permission.Permission] | None = None,
        pagination: _m_clappform_v1_commons_commons.Pagination | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_authoriser_v1_permission_permission.Permissions:
        """RPC: /clappform.authoriser.v1.permission.PermissionManagement/Create (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("permissions", permissions), ("pagination", pagination),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_authoriser_v1_permission_permission.Permissions, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.authoriser.v1.permission.PermissionManagement/Create",
            _request,
            _m_clappform_authoriser_v1_permission_permission.Permissions,
            _m_clappform_authoriser_v1_permission_permission.Permissions,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def delete(
        self,
        request: _m_clappform_v1_commons_commons.Read | None = None,
        *,
        id: str | None = None,
        detail_level: int | None = None,
        include_deleted: bool | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_v1_commons_commons.Message:
        """RPC: /clappform.authoriser.v1.permission.PermissionManagement/Delete (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("id", id), ("detail_level", detail_level), ("include_deleted", include_deleted),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_v1_commons_commons.Read, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.authoriser.v1.permission.PermissionManagement/Delete",
            _request,
            _m_clappform_v1_commons_commons.Read,
            _m_clappform_v1_commons_commons.Message,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def delete_permissions(
        self,
        request: _m_clappform_authoriser_v1_permission_permission.Permissions | None = None,
        *,
        permissions: Sequence[_m_clappform_authoriser_v1_permission_permission.Permission] | None = None,
        pagination: _m_clappform_v1_commons_commons.Pagination | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_v1_commons_commons.Message:
        """RPC: /clappform.authoriser.v1.permission.PermissionManagement/DeletePermissions (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("permissions", permissions), ("pagination", pagination),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_authoriser_v1_permission_permission.Permissions, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.authoriser.v1.permission.PermissionManagement/DeletePermissions",
            _request,
            _m_clappform_authoriser_v1_permission_permission.Permissions,
            _m_clappform_v1_commons_commons.Message,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )


class RecoverManagement(_runtime.ServiceBase):
    """Wrapper for clappform.authoriser.v1.recover.RecoverManagement."""

    def request_password_reset(
        self,
        request: _m_clappform_authoriser_v1_recover_recover.ResetRequest | None = None,
        *,
        username: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_v1_commons_commons.Message:
        """RPC: /clappform.authoriser.v1.recover.RecoverManagement/RequestPasswordReset (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("username", username),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_authoriser_v1_recover_recover.ResetRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.authoriser.v1.recover.RecoverManagement/RequestPasswordReset",
            _request,
            _m_clappform_authoriser_v1_recover_recover.ResetRequest,
            _m_clappform_v1_commons_commons.Message,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def confirm_password_reset(
        self,
        request: _m_clappform_authoriser_v1_recover_recover.ConfirmResetRequest | None = None,
        *,
        reset_key: str | None = None,
        new_password: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_v1_commons_commons.Message:
        """RPC: /clappform.authoriser.v1.recover.RecoverManagement/ConfirmPasswordReset (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("reset_key", reset_key), ("new_password", new_password),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_authoriser_v1_recover_recover.ConfirmResetRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.authoriser.v1.recover.RecoverManagement/ConfirmPasswordReset",
            _request,
            _m_clappform_authoriser_v1_recover_recover.ConfirmResetRequest,
            _m_clappform_v1_commons_commons.Message,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )


class RoleManagement(_runtime.ServiceBase):
    """Wrapper for clappform.authoriser.v1.role.RoleManagement."""

    def read_all(
        self,
        request: _m_clappform_v1_commons_commons.PaginationRequest | None = None,
        *,
        page: int | None = None,
        limit: int | None = None,
        batch_size: int | None = None,
        query_parameters: str | None = None,
        include_deleted: bool | None = None,
        detail_level: int | None = None,
        sort: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_authoriser_v1_role_role.Roles:
        """RPC: /clappform.authoriser.v1.role.RoleManagement/ReadAll (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("page", page), ("limit", limit), ("batch_size", batch_size), ("query_parameters", query_parameters), ("include_deleted", include_deleted), ("detail_level", detail_level), ("sort", sort),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_v1_commons_commons.PaginationRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.authoriser.v1.role.RoleManagement/ReadAll",
            _request,
            _m_clappform_v1_commons_commons.PaginationRequest,
            _m_clappform_authoriser_v1_role_role.Roles,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def iter_read_all(
        self,
        *,
        limit: int | None = None,
        batch_size: int | None = None,
        query_parameters: str | None = None,
        include_deleted: bool | None = None,
        detail_level: int | None = None,
        sort: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> Iterator[_m_clappform_authoriser_v1_role_role.Role]:
        """Auto-paginating variant of ``read_all``.

        Yields each item from ``roles`` across all pages, following
        ``pagination`` until the last page.
        """
        _page = 1
        while True:
            _resp = self.read_all(page=_page, limit=limit, batch_size=batch_size, query_parameters=query_parameters, include_deleted=include_deleted, detail_level=detail_level, sort=sort, timeout=timeout, metadata=metadata, location=location)
            yield from _resp.roles
            _pagination = _resp.pagination
            if _pagination.pages <= _pagination.page:
                break
            _page = _pagination.page + 1

    def read(
        self,
        request: _m_clappform_v1_commons_commons.Read | None = None,
        *,
        id: str | None = None,
        detail_level: int | None = None,
        include_deleted: bool | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_authoriser_v1_role_role.Role:
        """RPC: /clappform.authoriser.v1.role.RoleManagement/Read (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("id", id), ("detail_level", detail_level), ("include_deleted", include_deleted),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_v1_commons_commons.Read, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.authoriser.v1.role.RoleManagement/Read",
            _request,
            _m_clappform_v1_commons_commons.Read,
            _m_clappform_authoriser_v1_role_role.Role,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def create(
        self,
        request: _m_clappform_authoriser_v1_role_role.CreateRequest | None = None,
        *,
        name: str | None = None,
        users: Sequence[str] | None = None,
        permissions: Sequence[_m_clappform_authoriser_v1_permission_permission.Permission] | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_authoriser_v1_role_role.Role:
        """RPC: /clappform.authoriser.v1.role.RoleManagement/Create (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("name", name), ("users", users), ("permissions", permissions),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_authoriser_v1_role_role.CreateRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.authoriser.v1.role.RoleManagement/Create",
            _request,
            _m_clappform_authoriser_v1_role_role.CreateRequest,
            _m_clappform_authoriser_v1_role_role.Role,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def update(
        self,
        request: _m_clappform_authoriser_v1_role_role.UpdateRequest | None = None,
        *,
        id: str | None = None,
        name: str | None = None,
        users: Sequence[str] | None = None,
        permissions: Sequence[_m_clappform_authoriser_v1_permission_permission.Permission] | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_authoriser_v1_role_role.Role:
        """RPC: /clappform.authoriser.v1.role.RoleManagement/Update (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("id", id), ("name", name), ("users", users), ("permissions", permissions),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_authoriser_v1_role_role.UpdateRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.authoriser.v1.role.RoleManagement/Update",
            _request,
            _m_clappform_authoriser_v1_role_role.UpdateRequest,
            _m_clappform_authoriser_v1_role_role.Role,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def delete(
        self,
        request: _m_clappform_v1_commons_commons.Read | None = None,
        *,
        id: str | None = None,
        detail_level: int | None = None,
        include_deleted: bool | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_v1_commons_commons.Message:
        """RPC: /clappform.authoriser.v1.role.RoleManagement/Delete (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("id", id), ("detail_level", detail_level), ("include_deleted", include_deleted),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_v1_commons_commons.Read, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.authoriser.v1.role.RoleManagement/Delete",
            _request,
            _m_clappform_v1_commons_commons.Read,
            _m_clappform_v1_commons_commons.Message,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )


class SecurityProfileManagement(_runtime.ServiceBase):
    """Wrapper for clappform.authoriser.v1.security_profile.SecurityProfileManagement."""

    def read_all(
        self,
        request: _m_clappform_v1_commons_commons.PaginationRequest | None = None,
        *,
        page: int | None = None,
        limit: int | None = None,
        batch_size: int | None = None,
        query_parameters: str | None = None,
        include_deleted: bool | None = None,
        detail_level: int | None = None,
        sort: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_authoriser_v1_security_profile_security_profile.Authorities:
        """RPC: /clappform.authoriser.v1.security_profile.SecurityProfileManagement/ReadAll (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("page", page), ("limit", limit), ("batch_size", batch_size), ("query_parameters", query_parameters), ("include_deleted", include_deleted), ("detail_level", detail_level), ("sort", sort),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_v1_commons_commons.PaginationRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.authoriser.v1.security_profile.SecurityProfileManagement/ReadAll",
            _request,
            _m_clappform_v1_commons_commons.PaginationRequest,
            _m_clappform_authoriser_v1_security_profile_security_profile.Authorities,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def iter_read_all(
        self,
        *,
        limit: int | None = None,
        batch_size: int | None = None,
        query_parameters: str | None = None,
        include_deleted: bool | None = None,
        detail_level: int | None = None,
        sort: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> Iterator[_m_clappform_authoriser_v1_security_profile_security_profile.Authority]:
        """Auto-paginating variant of ``read_all``.

        Yields each item from ``authorities`` across all pages, following
        ``pagination`` until the last page.
        """
        _page = 1
        while True:
            _resp = self.read_all(page=_page, limit=limit, batch_size=batch_size, query_parameters=query_parameters, include_deleted=include_deleted, detail_level=detail_level, sort=sort, timeout=timeout, metadata=metadata, location=location)
            yield from _resp.authorities
            _pagination = _resp.pagination
            if _pagination.pages <= _pagination.page:
                break
            _page = _pagination.page + 1

    def create_security_profile(
        self,
        request: _m_clappform_authoriser_v1_security_profile_security_profile.CreateProfile | None = None,
        *,
        authority: str | None = None,
        client_id: str | None = None,
        app_id: str | None = None,
        type: str | None = None,
        certificate: bytes | None = None,
        private_key: bytes | None = None,
        webhook_secret: bytes | None = None,
        default_roles: Sequence[str] | None = None,
        auto_initiate: bool | None = None,
        default_user_info: bytes | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_authoriser_v1_security_profile_security_profile.Authority:
        """RPC: /clappform.authoriser.v1.security_profile.SecurityProfileManagement/CreateSecurityProfile (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("authority", authority), ("client_id", client_id), ("app_id", app_id), ("type", type), ("certificate", certificate), ("private_key", private_key), ("webhook_secret", webhook_secret), ("default_roles", default_roles), ("auto_initiate", auto_initiate), ("default_user_info", default_user_info),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_authoriser_v1_security_profile_security_profile.CreateProfile, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.authoriser.v1.security_profile.SecurityProfileManagement/CreateSecurityProfile",
            _request,
            _m_clappform_authoriser_v1_security_profile_security_profile.CreateProfile,
            _m_clappform_authoriser_v1_security_profile_security_profile.Authority,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def update_security_profile(
        self,
        request: _m_clappform_authoriser_v1_security_profile_security_profile.UpdateProfile | None = None,
        *,
        authority: str | None = None,
        app_id: str | None = None,
        certificate: bytes | None = None,
        private_key: bytes | None = None,
        webhook_secret: bytes | None = None,
        default_roles: Sequence[str] | None = None,
        auto_initiate: bool | None = None,
        default_user_info: bytes | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_authoriser_v1_security_profile_security_profile.Authority:
        """RPC: /clappform.authoriser.v1.security_profile.SecurityProfileManagement/UpdateSecurityProfile (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("authority", authority), ("app_id", app_id), ("certificate", certificate), ("private_key", private_key), ("webhook_secret", webhook_secret), ("default_roles", default_roles), ("auto_initiate", auto_initiate), ("default_user_info", default_user_info),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_authoriser_v1_security_profile_security_profile.UpdateProfile, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.authoriser.v1.security_profile.SecurityProfileManagement/UpdateSecurityProfile",
            _request,
            _m_clappform_authoriser_v1_security_profile_security_profile.UpdateProfile,
            _m_clappform_authoriser_v1_security_profile_security_profile.Authority,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )


class UserManagement(_runtime.ServiceBase):
    """Wrapper for clappform.authoriser.v1.user.UserManagement."""

    def read_all(
        self,
        request: _m_clappform_v1_commons_commons.PaginationRequest | None = None,
        *,
        page: int | None = None,
        limit: int | None = None,
        batch_size: int | None = None,
        query_parameters: str | None = None,
        include_deleted: bool | None = None,
        detail_level: int | None = None,
        sort: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_authoriser_v1_user_user.Users:
        """RPC: /clappform.authoriser.v1.user.UserManagement/ReadAll (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("page", page), ("limit", limit), ("batch_size", batch_size), ("query_parameters", query_parameters), ("include_deleted", include_deleted), ("detail_level", detail_level), ("sort", sort),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_v1_commons_commons.PaginationRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.authoriser.v1.user.UserManagement/ReadAll",
            _request,
            _m_clappform_v1_commons_commons.PaginationRequest,
            _m_clappform_authoriser_v1_user_user.Users,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def iter_read_all(
        self,
        *,
        limit: int | None = None,
        batch_size: int | None = None,
        query_parameters: str | None = None,
        include_deleted: bool | None = None,
        detail_level: int | None = None,
        sort: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> Iterator[_m_clappform_authoriser_v1_user_user.User]:
        """Auto-paginating variant of ``read_all``.

        Yields each item from ``users`` across all pages, following
        ``pagination`` until the last page.
        """
        _page = 1
        while True:
            _resp = self.read_all(page=_page, limit=limit, batch_size=batch_size, query_parameters=query_parameters, include_deleted=include_deleted, detail_level=detail_level, sort=sort, timeout=timeout, metadata=metadata, location=location)
            yield from _resp.users
            _pagination = _resp.pagination
            if _pagination.pages <= _pagination.page:
                break
            _page = _pagination.page + 1

    def read(
        self,
        request: _m_clappform_v1_commons_commons.Read | None = None,
        *,
        id: str | None = None,
        detail_level: int | None = None,
        include_deleted: bool | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_authoriser_v1_user_user.User:
        """RPC: /clappform.authoriser.v1.user.UserManagement/Read (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("id", id), ("detail_level", detail_level), ("include_deleted", include_deleted),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_v1_commons_commons.Read, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.authoriser.v1.user.UserManagement/Read",
            _request,
            _m_clappform_v1_commons_commons.Read,
            _m_clappform_authoriser_v1_user_user.User,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def create(
        self,
        request: _m_clappform_authoriser_v1_user_user.CreateRequest | None = None,
        *,
        email: str | None = None,
        first_name: str | None = None,
        last_name: str | None = None,
        password: str | None = None,
        is_active: bool | None = None,
        extra_information: bytes | None = None,
        roles: Sequence[str] | None = None,
        preferences: bytes | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_authoriser_v1_user_user.User:
        """RPC: /clappform.authoriser.v1.user.UserManagement/Create (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("email", email), ("first_name", first_name), ("last_name", last_name), ("password", password), ("is_active", is_active), ("extra_information", extra_information), ("roles", roles), ("preferences", preferences),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_authoriser_v1_user_user.CreateRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.authoriser.v1.user.UserManagement/Create",
            _request,
            _m_clappform_authoriser_v1_user_user.CreateRequest,
            _m_clappform_authoriser_v1_user_user.User,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def update(
        self,
        request: _m_clappform_authoriser_v1_user_user.UpdateRequest | None = None,
        *,
        id: str | None = None,
        email: str | None = None,
        first_name: str | None = None,
        last_name: str | None = None,
        password: str | None = None,
        extra_information: bytes | None = None,
        roles: Sequence[str] | None = None,
        preferences: bytes | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_authoriser_v1_user_user.User:
        """RPC: /clappform.authoriser.v1.user.UserManagement/Update (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("id", id), ("email", email), ("first_name", first_name), ("last_name", last_name), ("password", password), ("extra_information", extra_information), ("roles", roles), ("preferences", preferences),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_authoriser_v1_user_user.UpdateRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.authoriser.v1.user.UserManagement/Update",
            _request,
            _m_clappform_authoriser_v1_user_user.UpdateRequest,
            _m_clappform_authoriser_v1_user_user.User,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def disable(
        self,
        request: _m_clappform_v1_commons_commons.Read | None = None,
        *,
        id: str | None = None,
        detail_level: int | None = None,
        include_deleted: bool | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_v1_commons_commons.Message:
        """RPC: /clappform.authoriser.v1.user.UserManagement/Disable (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("id", id), ("detail_level", detail_level), ("include_deleted", include_deleted),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_v1_commons_commons.Read, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.authoriser.v1.user.UserManagement/Disable",
            _request,
            _m_clappform_v1_commons_commons.Read,
            _m_clappform_v1_commons_commons.Message,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def enable(
        self,
        request: _m_clappform_v1_commons_commons.Read | None = None,
        *,
        id: str | None = None,
        detail_level: int | None = None,
        include_deleted: bool | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_v1_commons_commons.Message:
        """RPC: /clappform.authoriser.v1.user.UserManagement/Enable (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("id", id), ("detail_level", detail_level), ("include_deleted", include_deleted),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_v1_commons_commons.Read, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.authoriser.v1.user.UserManagement/Enable",
            _request,
            _m_clappform_v1_commons_commons.Read,
            _m_clappform_v1_commons_commons.Message,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def delete(
        self,
        request: _m_clappform_v1_commons_commons.Read | None = None,
        *,
        id: str | None = None,
        detail_level: int | None = None,
        include_deleted: bool | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_v1_commons_commons.Message:
        """RPC: /clappform.authoriser.v1.user.UserManagement/Delete (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("id", id), ("detail_level", detail_level), ("include_deleted", include_deleted),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_v1_commons_commons.Read, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.authoriser.v1.user.UserManagement/Delete",
            _request,
            _m_clappform_v1_commons_commons.Read,
            _m_clappform_v1_commons_commons.Message,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )


class VersionManagement(_runtime.ServiceBase):
    """Wrapper for clappform.authoriser.v1.version.VersionManagement."""

    def get_all(
        self,
        request: _m_clappform_v1_commons_commons.PaginationRequest | None = None,
        *,
        page: int | None = None,
        limit: int | None = None,
        batch_size: int | None = None,
        query_parameters: str | None = None,
        include_deleted: bool | None = None,
        detail_level: int | None = None,
        sort: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_authoriser_v1_version_version.Versions:
        """RPC: /clappform.authoriser.v1.version.VersionManagement/GetAll (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("page", page), ("limit", limit), ("batch_size", batch_size), ("query_parameters", query_parameters), ("include_deleted", include_deleted), ("detail_level", detail_level), ("sort", sort),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_v1_commons_commons.PaginationRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.authoriser.v1.version.VersionManagement/GetAll",
            _request,
            _m_clappform_v1_commons_commons.PaginationRequest,
            _m_clappform_authoriser_v1_version_version.Versions,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def iter_get_all(
        self,
        *,
        limit: int | None = None,
        batch_size: int | None = None,
        query_parameters: str | None = None,
        include_deleted: bool | None = None,
        detail_level: int | None = None,
        sort: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> Iterator[_m_clappform_authoriser_v1_version_version.Version]:
        """Auto-paginating variant of ``get_all``.

        Yields each item from ``versions`` across all pages, following
        ``pagination`` until the last page.
        """
        _page = 1
        while True:
            _resp = self.get_all(page=_page, limit=limit, batch_size=batch_size, query_parameters=query_parameters, include_deleted=include_deleted, detail_level=detail_level, sort=sort, timeout=timeout, metadata=metadata, location=location)
            yield from _resp.versions
            _pagination = _resp.pagination
            if _pagination.pages <= _pagination.page:
                break
            _page = _pagination.page + 1

    def get(
        self,
        request: _m_clappform_v1_commons_commons.Read | None = None,
        *,
        id: str | None = None,
        detail_level: int | None = None,
        include_deleted: bool | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_authoriser_v1_version_version.Version:
        """RPC: /clappform.authoriser.v1.version.VersionManagement/Get (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("id", id), ("detail_level", detail_level), ("include_deleted", include_deleted),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_v1_commons_commons.Read, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.authoriser.v1.version.VersionManagement/Get",
            _request,
            _m_clappform_v1_commons_commons.Read,
            _m_clappform_authoriser_v1_version_version.Version,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def revert(
        self,
        request: _m_clappform_v1_commons_commons.Read | None = None,
        *,
        id: str | None = None,
        detail_level: int | None = None,
        include_deleted: bool | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_v1_commons_commons.Message:
        """RPC: /clappform.authoriser.v1.version.VersionManagement/Revert (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("id", id), ("detail_level", detail_level), ("include_deleted", include_deleted),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_v1_commons_commons.Read, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.authoriser.v1.version.VersionManagement/Revert",
            _request,
            _m_clappform_v1_commons_commons.Read,
            _m_clappform_v1_commons_commons.Message,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def lock(
        self,
        request: _m_clappform_v1_commons_commons.Read | None = None,
        *,
        id: str | None = None,
        detail_level: int | None = None,
        include_deleted: bool | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_v1_commons_commons.Message:
        """RPC: /clappform.authoriser.v1.version.VersionManagement/Lock (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("id", id), ("detail_level", detail_level), ("include_deleted", include_deleted),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_v1_commons_commons.Read, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.authoriser.v1.version.VersionManagement/Lock",
            _request,
            _m_clappform_v1_commons_commons.Read,
            _m_clappform_v1_commons_commons.Message,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def unlock(
        self,
        request: _m_clappform_v1_commons_commons.Read | None = None,
        *,
        id: str | None = None,
        detail_level: int | None = None,
        include_deleted: bool | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_v1_commons_commons.Message:
        """RPC: /clappform.authoriser.v1.version.VersionManagement/Unlock (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("id", id), ("detail_level", detail_level), ("include_deleted", include_deleted),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_v1_commons_commons.Read, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.authoriser.v1.version.VersionManagement/Unlock",
            _request,
            _m_clappform_v1_commons_commons.Read,
            _m_clappform_v1_commons_commons.Message,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )


class AuthAPI:
    """Generated sub-client for the authoriser API."""

    def __init__(self, caller: _runtime.Caller) -> None:
        self.api_key = APIKeyManagement(caller)
        self.azure = AzureManagement(caller)
        self.general = GeneralManagement(caller)
        self.guest_key = GuestKeyManagement(caller)
        self.otp = OtpManagement(caller)
        self.password = PasswordManagement(caller)
        self.permission = PermissionManagement(caller)
        self.recover = RecoverManagement(caller)
        self.role = RoleManagement(caller)
        self.security_profile = SecurityProfileManagement(caller)
        self.user = UserManagement(caller)
        self.version = VersionManagement(caller)
