"""Generated by tools/generate.py — do not edit."""

from __future__ import annotations

from collections.abc import Iterable, Iterator, Sequence
from typing import Any

from clappform import _runtime
import clappform.gen.clappform.data.v1.aggregate.aggregate_pb2 as _m_clappform_data_v1_aggregate_aggregate
import clappform.gen.clappform.data.v1.change_request.change_request_pb2 as _m_clappform_data_v1_change_request_change_request
import clappform.gen.clappform.data.v1.chat.chat_pb2 as _m_clappform_data_v1_chat_chat
import clappform.gen.clappform.data.v1.delete.delete_pb2 as _m_clappform_data_v1_delete_delete
import clappform.gen.clappform.data.v1.general.general_pb2 as _m_clappform_data_v1_general_general
import clappform.gen.clappform.data.v1.index.index_pb2 as _m_clappform_data_v1_index_index
import clappform.gen.clappform.data.v1.insert.insert_pb2 as _m_clappform_data_v1_insert_insert
import clappform.gen.clappform.data.v1.process.process_pb2 as _m_clappform_data_v1_process_process
import clappform.gen.clappform.data.v1.sync.sync_pb2 as _m_clappform_data_v1_sync_sync
import clappform.gen.clappform.data.v1.update.update_pb2 as _m_clappform_data_v1_update_update
import clappform.gen.clappform.v1.commons.commons_pb2 as _m_clappform_v1_commons_commons
import google.protobuf.struct_pb2 as _m_google_protobuf_struct


class AggregateManagement(_runtime.ServiceBase):
    """Wrapper for clappform.data.v1.aggregate.AggregateManagement."""

    def aggregate_stream(
        self,
        request: _m_clappform_data_v1_aggregate_aggregate.AggregateStreamRequest | None = None,
        *,
        pipeline: bytes | None = None,
        batch_size: int | None = None,
        collection: str | None = None,
        query: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> Iterator[_m_clappform_data_v1_aggregate_aggregate.AggregateResponse]:
        """RPC: /clappform.data.v1.aggregate.AggregateManagement/AggregateStream (unary-stream)"""
        _provided = {_k: _v for _k, _v in (("pipeline", pipeline), ("batch_size", batch_size), ("collection", collection), ("query", query),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_data_v1_aggregate_aggregate.AggregateStreamRequest, request, _provided)
        return self._caller.invoke(
            "unary_stream",
            "/clappform.data.v1.aggregate.AggregateManagement/AggregateStream",
            _request,
            _m_clappform_data_v1_aggregate_aggregate.AggregateStreamRequest,
            _m_clappform_data_v1_aggregate_aggregate.AggregateResponse,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def aggregate_unary(
        self,
        request: _m_clappform_data_v1_aggregate_aggregate.AggregateUnaryRequest | None = None,
        *,
        pipeline: bytes | None = None,
        batch_size: int | None = None,
        collection: str | None = None,
        query: str | None = None,
        filter_options: _m_clappform_data_v1_aggregate_aggregate.AggregateFilterOptions | None = None,
        deep_dive: bytes | None = None,
        options: bytes | None = None,
        inner_options: bytes | None = None,
        next_page: int | None = None,
        search: bytes | None = None,
        bounds: _m_clappform_data_v1_aggregate_aggregate.BoundsRequest | None = None,
        sorting: bytes | None = None,
        explain: bool | None = None,
        custom_match: bytes | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_data_v1_aggregate_aggregate.AggregateResponse:
        """RPC: /clappform.data.v1.aggregate.AggregateManagement/AggregateUnary (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("pipeline", pipeline), ("batch_size", batch_size), ("collection", collection), ("query", query), ("filter_options", filter_options), ("deep_dive", deep_dive), ("options", options), ("inner_options", inner_options), ("next_page", next_page), ("search", search), ("bounds", bounds), ("sorting", sorting), ("explain", explain), ("custom_match", custom_match),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_data_v1_aggregate_aggregate.AggregateUnaryRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.data.v1.aggregate.AggregateManagement/AggregateUnary",
            _request,
            _m_clappform_data_v1_aggregate_aggregate.AggregateUnaryRequest,
            _m_clappform_data_v1_aggregate_aggregate.AggregateResponse,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )


class ChangeRequestManagement(_runtime.ServiceBase):
    """Wrapper for clappform.data.v1.change_request.ChangeRequestManagement."""

    def request_change(
        self,
        request: _m_clappform_data_v1_change_request_change_request.ChangeRequest | None = None,
        *,
        data: bytes | None = None,
        collection: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_data_v1_change_request_change_request.RequestChangeResponse:
        """RPC: /clappform.data.v1.change_request.ChangeRequestManagement/RequestChange (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("data", data), ("collection", collection),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_data_v1_change_request_change_request.ChangeRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.data.v1.change_request.ChangeRequestManagement/RequestChange",
            _request,
            _m_clappform_data_v1_change_request_change_request.ChangeRequest,
            _m_clappform_data_v1_change_request_change_request.RequestChangeResponse,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def modify_change(
        self,
        request: _m_clappform_data_v1_change_request_change_request.ModifyChangeRequest | None = None,
        *,
        request_id: str | None = None,
        collection: str | None = None,
        note: str | None = None,
        data: bytes | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_data_v1_change_request_change_request.RequestChangeResponse:
        """RPC: /clappform.data.v1.change_request.ChangeRequestManagement/ModifyChange (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("request_id", request_id), ("collection", collection), ("note", note), ("data", data),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_data_v1_change_request_change_request.ModifyChangeRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.data.v1.change_request.ChangeRequestManagement/ModifyChange",
            _request,
            _m_clappform_data_v1_change_request_change_request.ModifyChangeRequest,
            _m_clappform_data_v1_change_request_change_request.RequestChangeResponse,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def approve_change(
        self,
        request: _m_clappform_data_v1_change_request_change_request.UpdateStatusRequest | None = None,
        *,
        request_id: str | None = None,
        collection: str | None = None,
        note: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_data_v1_change_request_change_request.RequestChangeResponse:
        """RPC: /clappform.data.v1.change_request.ChangeRequestManagement/ApproveChange (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("request_id", request_id), ("collection", collection), ("note", note),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_data_v1_change_request_change_request.UpdateStatusRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.data.v1.change_request.ChangeRequestManagement/ApproveChange",
            _request,
            _m_clappform_data_v1_change_request_change_request.UpdateStatusRequest,
            _m_clappform_data_v1_change_request_change_request.RequestChangeResponse,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def reject_change(
        self,
        request: _m_clappform_data_v1_change_request_change_request.UpdateStatusRequest | None = None,
        *,
        request_id: str | None = None,
        collection: str | None = None,
        note: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_data_v1_change_request_change_request.RequestChangeResponse:
        """RPC: /clappform.data.v1.change_request.ChangeRequestManagement/RejectChange (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("request_id", request_id), ("collection", collection), ("note", note),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_data_v1_change_request_change_request.UpdateStatusRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.data.v1.change_request.ChangeRequestManagement/RejectChange",
            _request,
            _m_clappform_data_v1_change_request_change_request.UpdateStatusRequest,
            _m_clappform_data_v1_change_request_change_request.RequestChangeResponse,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def review_change(
        self,
        request: _m_clappform_data_v1_change_request_change_request.UpdateStatusRequest | None = None,
        *,
        request_id: str | None = None,
        collection: str | None = None,
        note: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_data_v1_change_request_change_request.RequestChangeResponse:
        """RPC: /clappform.data.v1.change_request.ChangeRequestManagement/ReviewChange (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("request_id", request_id), ("collection", collection), ("note", note),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_data_v1_change_request_change_request.UpdateStatusRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.data.v1.change_request.ChangeRequestManagement/ReviewChange",
            _request,
            _m_clappform_data_v1_change_request_change_request.UpdateStatusRequest,
            _m_clappform_data_v1_change_request_change_request.RequestChangeResponse,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def withdraw_change(
        self,
        request: _m_clappform_data_v1_change_request_change_request.UpdateStatusRequest | None = None,
        *,
        request_id: str | None = None,
        collection: str | None = None,
        note: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_data_v1_change_request_change_request.RequestChangeResponse:
        """RPC: /clappform.data.v1.change_request.ChangeRequestManagement/WithdrawChange (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("request_id", request_id), ("collection", collection), ("note", note),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_data_v1_change_request_change_request.UpdateStatusRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.data.v1.change_request.ChangeRequestManagement/WithdrawChange",
            _request,
            _m_clappform_data_v1_change_request_change_request.UpdateStatusRequest,
            _m_clappform_data_v1_change_request_change_request.RequestChangeResponse,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def add_comment(
        self,
        request: _m_clappform_data_v1_change_request_change_request.UpdateStatusRequest | None = None,
        *,
        request_id: str | None = None,
        collection: str | None = None,
        note: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_data_v1_change_request_change_request.RequestChangeResponse:
        """RPC: /clappform.data.v1.change_request.ChangeRequestManagement/AddComment (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("request_id", request_id), ("collection", collection), ("note", note),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_data_v1_change_request_change_request.UpdateStatusRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.data.v1.change_request.ChangeRequestManagement/AddComment",
            _request,
            _m_clappform_data_v1_change_request_change_request.UpdateStatusRequest,
            _m_clappform_data_v1_change_request_change_request.RequestChangeResponse,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def add_approver(
        self,
        request: _m_clappform_data_v1_change_request_change_request.ModifyApproverRequest | None = None,
        *,
        request_id: str | None = None,
        collection: str | None = None,
        note: str | None = None,
        approver_id: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_data_v1_change_request_change_request.RequestChangeResponse:
        """RPC: /clappform.data.v1.change_request.ChangeRequestManagement/AddApprover (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("request_id", request_id), ("collection", collection), ("note", note), ("approver_id", approver_id),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_data_v1_change_request_change_request.ModifyApproverRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.data.v1.change_request.ChangeRequestManagement/AddApprover",
            _request,
            _m_clappform_data_v1_change_request_change_request.ModifyApproverRequest,
            _m_clappform_data_v1_change_request_change_request.RequestChangeResponse,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def remove_approver(
        self,
        request: _m_clappform_data_v1_change_request_change_request.ModifyApproverRequest | None = None,
        *,
        request_id: str | None = None,
        collection: str | None = None,
        note: str | None = None,
        approver_id: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_data_v1_change_request_change_request.RequestChangeResponse:
        """RPC: /clappform.data.v1.change_request.ChangeRequestManagement/RemoveApprover (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("request_id", request_id), ("collection", collection), ("note", note), ("approver_id", approver_id),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_data_v1_change_request_change_request.ModifyApproverRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.data.v1.change_request.ChangeRequestManagement/RemoveApprover",
            _request,
            _m_clappform_data_v1_change_request_change_request.ModifyApproverRequest,
            _m_clappform_data_v1_change_request_change_request.RequestChangeResponse,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )


class ChatManagement(_runtime.ServiceBase):
    """Wrapper for clappform.data.v1.chat.ChatManagement."""

    def get_rooms(
        self,
        request: _m_clappform_data_v1_chat_chat.GetRoomsRequest | None = None,
        *,
        app_id: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_data_v1_chat_chat.Rooms:
        """RPC: /clappform.data.v1.chat.ChatManagement/GetRooms (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("app_id", app_id),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_data_v1_chat_chat.GetRoomsRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.data.v1.chat.ChatManagement/GetRooms",
            _request,
            _m_clappform_data_v1_chat_chat.GetRoomsRequest,
            _m_clappform_data_v1_chat_chat.Rooms,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def update_room(
        self,
        request: _m_clappform_data_v1_chat_chat.UpdateRoomRequest | None = None,
        *,
        id: str | None = None,
        room: _m_clappform_data_v1_chat_chat.RoomUpdate | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_data_v1_chat_chat.Room:
        """RPC: /clappform.data.v1.chat.ChatManagement/UpdateRoom (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("id", id), ("room", room),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_data_v1_chat_chat.UpdateRoomRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.data.v1.chat.ChatManagement/UpdateRoom",
            _request,
            _m_clappform_data_v1_chat_chat.UpdateRoomRequest,
            _m_clappform_data_v1_chat_chat.Room,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def delete_room(
        self,
        request: _m_clappform_data_v1_chat_chat.DeleteRoomRequest | None = None,
        *,
        app_id: str | None = None,
        id: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_v1_commons_commons.Empty:
        """RPC: /clappform.data.v1.chat.ChatManagement/DeleteRoom (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("app_id", app_id), ("id", id),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_data_v1_chat_chat.DeleteRoomRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.data.v1.chat.ChatManagement/DeleteRoom",
            _request,
            _m_clappform_data_v1_chat_chat.DeleteRoomRequest,
            _m_clappform_v1_commons_commons.Empty,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def stream_message(
        self,
        request: _m_clappform_data_v1_chat_chat.StreamMessageRequest | None = None,
        *,
        id: str | None = None,
        payload: _m_clappform_data_v1_chat_chat.StreamMessageRequestPayload | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> Iterator[_m_clappform_data_v1_chat_chat.StreamMessageResponse]:
        """RPC: /clappform.data.v1.chat.ChatManagement/StreamMessage (unary-stream)"""
        _provided = {_k: _v for _k, _v in (("id", id), ("payload", payload),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_data_v1_chat_chat.StreamMessageRequest, request, _provided)
        return self._caller.invoke(
            "unary_stream",
            "/clappform.data.v1.chat.ChatManagement/StreamMessage",
            _request,
            _m_clappform_data_v1_chat_chat.StreamMessageRequest,
            _m_clappform_data_v1_chat_chat.StreamMessageResponse,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def get_messages(
        self,
        request: _m_clappform_data_v1_chat_chat.GetMessagesRequest | None = None,
        *,
        app_id: str | None = None,
        id: str | None = None,
        cursor: int | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_data_v1_chat_chat.Messages:
        """RPC: /clappform.data.v1.chat.ChatManagement/GetMessages (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("app_id", app_id), ("id", id), ("cursor", cursor),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_data_v1_chat_chat.GetMessagesRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.data.v1.chat.ChatManagement/GetMessages",
            _request,
            _m_clappform_data_v1_chat_chat.GetMessagesRequest,
            _m_clappform_data_v1_chat_chat.Messages,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def upload_files(
        self,
        request: _m_clappform_data_v1_chat_chat.FileUploadRequest | None = None,
        *,
        filenames: Sequence[str] | None = None,
        collection: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_data_v1_chat_chat.FileUploadResponse:
        """RPC: /clappform.data.v1.chat.ChatManagement/UploadFiles (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("filenames", filenames), ("collection", collection),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_data_v1_chat_chat.FileUploadRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.data.v1.chat.ChatManagement/UploadFiles",
            _request,
            _m_clappform_data_v1_chat_chat.FileUploadRequest,
            _m_clappform_data_v1_chat_chat.FileUploadResponse,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def delete_file(
        self,
        request: _m_clappform_data_v1_chat_chat.FileDeleteRequest | None = None,
        *,
        document_id: str | None = None,
        collection: str | None = None,
        filename: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_v1_commons_commons.Empty:
        """RPC: /clappform.data.v1.chat.ChatManagement/DeleteFile (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("document_id", document_id), ("collection", collection), ("filename", filename),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_data_v1_chat_chat.FileDeleteRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.data.v1.chat.ChatManagement/DeleteFile",
            _request,
            _m_clappform_data_v1_chat_chat.FileDeleteRequest,
            _m_clappform_v1_commons_commons.Empty,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )


class DeleteManagement(_runtime.ServiceBase):
    """Wrapper for clappform.data.v1.delete.DeleteManagement."""

    def delete_many_by_oids(
        self,
        request: _m_clappform_data_v1_delete_delete.DeleteRequestOids | None = None,
        *,
        oids: Sequence[str] | None = None,
        collection: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_v1_commons_commons.Message:
        """RPC: /clappform.data.v1.delete.DeleteManagement/DeleteManyByOids (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("oids", oids), ("collection", collection),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_data_v1_delete_delete.DeleteRequestOids, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.data.v1.delete.DeleteManagement/DeleteManyByOids",
            _request,
            _m_clappform_data_v1_delete_delete.DeleteRequestOids,
            _m_clappform_v1_commons_commons.Message,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def delete_many_by_field(
        self,
        request: _m_clappform_data_v1_delete_delete.DeleteRequestByField | None = None,
        *,
        ids: bytes | None = None,
        collection: str | None = None,
        field_name: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_v1_commons_commons.Message:
        """RPC: /clappform.data.v1.delete.DeleteManagement/DeleteManyByField (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("ids", ids), ("collection", collection), ("field_name", field_name),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_data_v1_delete_delete.DeleteRequestByField, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.data.v1.delete.DeleteManagement/DeleteManyByField",
            _request,
            _m_clappform_data_v1_delete_delete.DeleteRequestByField,
            _m_clappform_v1_commons_commons.Message,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def delete_many_by_query(
        self,
        request: _m_clappform_data_v1_delete_delete.DeleteRequestQuery | None = None,
        *,
        query: bytes | None = None,
        collection: str | None = None,
        dry_run: bool | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_data_v1_delete_delete.DataResponse:
        """RPC: /clappform.data.v1.delete.DeleteManagement/DeleteManyByQuery (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("query", query), ("collection", collection), ("dry_run", dry_run),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_data_v1_delete_delete.DeleteRequestQuery, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.data.v1.delete.DeleteManagement/DeleteManyByQuery",
            _request,
            _m_clappform_data_v1_delete_delete.DeleteRequestQuery,
            _m_clappform_data_v1_delete_delete.DataResponse,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def clear(
        self,
        request: _m_clappform_data_v1_delete_delete.ClearRequest | None = None,
        *,
        collection: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_v1_commons_commons.Message:
        """RPC: /clappform.data.v1.delete.DeleteManagement/Clear (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("collection", collection),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_data_v1_delete_delete.ClearRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.data.v1.delete.DeleteManagement/Clear",
            _request,
            _m_clappform_data_v1_delete_delete.ClearRequest,
            _m_clappform_v1_commons_commons.Message,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )


class GeneralManagement(_runtime.ServiceBase):
    """Wrapper for clappform.data.v1.general.GeneralManagement."""

    def general(
        self,
        request: _m_clappform_v1_commons_commons.Empty | None = None,
        *,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_data_v1_general_general.LandingPage:
        """RPC: /clappform.data.v1.general.GeneralManagement/General (unary-unary)"""
        _provided: dict[str, Any] = {}
        _request = _runtime.build_request(_m_clappform_v1_commons_commons.Empty, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.data.v1.general.GeneralManagement/General",
            _request,
            _m_clappform_v1_commons_commons.Empty,
            _m_clappform_data_v1_general_general.LandingPage,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )


class IndexManagement(_runtime.ServiceBase):
    """Wrapper for clappform.data.v1.index.IndexManagement."""

    def get_all(
        self,
        request: _m_clappform_data_v1_index_index.ListIndexesRequest | None = None,
        *,
        collection: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_data_v1_index_index.ListIndexesResponse:
        """RPC: /clappform.data.v1.index.IndexManagement/GetAll (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("collection", collection),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_data_v1_index_index.ListIndexesRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.data.v1.index.IndexManagement/GetAll",
            _request,
            _m_clappform_data_v1_index_index.ListIndexesRequest,
            _m_clappform_data_v1_index_index.ListIndexesResponse,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def get(
        self,
        request: _m_clappform_data_v1_index_index.GetIndexDetailsRequest | None = None,
        *,
        collection: str | None = None,
        index_name: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_data_v1_index_index.GetIndexDetailsResponse:
        """RPC: /clappform.data.v1.index.IndexManagement/Get (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("collection", collection), ("index_name", index_name),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_data_v1_index_index.GetIndexDetailsRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.data.v1.index.IndexManagement/Get",
            _request,
            _m_clappform_data_v1_index_index.GetIndexDetailsRequest,
            _m_clappform_data_v1_index_index.GetIndexDetailsResponse,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def create(
        self,
        request: _m_clappform_data_v1_index_index.CreateIndexRequest | None = None,
        *,
        collection: str | None = None,
        index_name: str | None = None,
        mongo_index_model: _m_clappform_data_v1_index_index.MongoIndexModel | None = None,
        elastic_settings: bytes | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_data_v1_index_index.CreateIndexResponse:
        """RPC: /clappform.data.v1.index.IndexManagement/Create (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("collection", collection), ("index_name", index_name), ("mongo_index_model", mongo_index_model), ("elastic_settings", elastic_settings),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_data_v1_index_index.CreateIndexRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.data.v1.index.IndexManagement/Create",
            _request,
            _m_clappform_data_v1_index_index.CreateIndexRequest,
            _m_clappform_data_v1_index_index.CreateIndexResponse,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def update(
        self,
        request: _m_clappform_data_v1_index_index.UpdateIndexRequest | None = None,
        *,
        collection: str | None = None,
        index_name: str | None = None,
        mongo_index_model: _m_clappform_data_v1_index_index.MongoIndexModel | None = None,
        elastic_settings: bytes | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_data_v1_index_index.UpdateIndexResponse:
        """RPC: /clappform.data.v1.index.IndexManagement/Update (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("collection", collection), ("index_name", index_name), ("mongo_index_model", mongo_index_model), ("elastic_settings", elastic_settings),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_data_v1_index_index.UpdateIndexRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.data.v1.index.IndexManagement/Update",
            _request,
            _m_clappform_data_v1_index_index.UpdateIndexRequest,
            _m_clappform_data_v1_index_index.UpdateIndexResponse,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def delete(
        self,
        request: _m_clappform_data_v1_index_index.DeleteIndexRequest | None = None,
        *,
        collection: str | None = None,
        index_name: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_data_v1_index_index.DeleteIndexResponse:
        """RPC: /clappform.data.v1.index.IndexManagement/Delete (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("collection", collection), ("index_name", index_name),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_data_v1_index_index.DeleteIndexRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.data.v1.index.IndexManagement/Delete",
            _request,
            _m_clappform_data_v1_index_index.DeleteIndexRequest,
            _m_clappform_data_v1_index_index.DeleteIndexResponse,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )


class InsertManagement(_runtime.ServiceBase):
    """Wrapper for clappform.data.v1.insert.InsertManagement."""

    def insert_many(
        self,
        requests: Iterable[_m_clappform_data_v1_insert_insert.InsertRequest],
        *,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> Iterator[_m_clappform_data_v1_insert_insert.InsertResponse]:
        """RPC: /clappform.data.v1.insert.InsertManagement/InsertMany (stream-stream)"""
        _requests = _runtime.ensure_iterable(requests, _m_clappform_data_v1_insert_insert.InsertRequest)
        return self._caller.invoke(
            "stream_stream",
            "/clappform.data.v1.insert.InsertManagement/InsertMany",
            _requests,
            _m_clappform_data_v1_insert_insert.InsertRequest,
            _m_clappform_data_v1_insert_insert.InsertResponse,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def insert_single(
        self,
        request: _m_clappform_data_v1_insert_insert.InsertRequest | None = None,
        *,
        data: bytes | None = None,
        collection: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_data_v1_insert_insert.InsertResponse:
        """RPC: /clappform.data.v1.insert.InsertManagement/InsertSingle (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("data", data), ("collection", collection),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_data_v1_insert_insert.InsertRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.data.v1.insert.InsertManagement/InsertSingle",
            _request,
            _m_clappform_data_v1_insert_insert.InsertRequest,
            _m_clappform_data_v1_insert_insert.InsertResponse,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def insert_patched(
        self,
        requests: Iterable[_m_clappform_data_v1_insert_insert.InsertRequest],
        *,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_data_v1_insert_insert.PatchResponse:
        """RPC: /clappform.data.v1.insert.InsertManagement/InsertPatched (stream-unary)"""
        _requests = _runtime.ensure_iterable(requests, _m_clappform_data_v1_insert_insert.InsertRequest)
        return self._caller.invoke(
            "stream_unary",
            "/clappform.data.v1.insert.InsertManagement/InsertPatched",
            _requests,
            _m_clappform_data_v1_insert_insert.InsertRequest,
            _m_clappform_data_v1_insert_insert.PatchResponse,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )


class ProcessManagement(_runtime.ServiceBase):
    """Wrapper for clappform.data.v1.process.ProcessManagement."""

    def get_conformance(
        self,
        request: _m_clappform_data_v1_process_process.GetConformanceRequest | None = None,
        *,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_data_v1_process_process.ConformanceDeclaration:
        """RPC: /clappform.data.v1.process.ProcessManagement/GetConformance (unary-unary)"""
        _provided: dict[str, Any] = {}
        _request = _runtime.build_request(_m_clappform_data_v1_process_process.GetConformanceRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.data.v1.process.ProcessManagement/GetConformance",
            _request,
            _m_clappform_data_v1_process_process.GetConformanceRequest,
            _m_clappform_data_v1_process_process.ConformanceDeclaration,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def list_processes(
        self,
        request: _m_clappform_data_v1_process_process.ListProcessesRequest | None = None,
        *,
        limit: int | None = None,
        offset: int | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_data_v1_process_process.ProcessList:
        """RPC: /clappform.data.v1.process.ProcessManagement/ListProcesses (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("limit", limit), ("offset", offset),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_data_v1_process_process.ListProcessesRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.data.v1.process.ProcessManagement/ListProcesses",
            _request,
            _m_clappform_data_v1_process_process.ListProcessesRequest,
            _m_clappform_data_v1_process_process.ProcessList,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def describe_process(
        self,
        request: _m_clappform_data_v1_process_process.DescribeProcessRequest | None = None,
        *,
        process_id: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_data_v1_process_process.ProcessDescription:
        """RPC: /clappform.data.v1.process.ProcessManagement/DescribeProcess (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("process_id", process_id),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_data_v1_process_process.DescribeProcessRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.data.v1.process.ProcessManagement/DescribeProcess",
            _request,
            _m_clappform_data_v1_process_process.DescribeProcessRequest,
            _m_clappform_data_v1_process_process.ProcessDescription,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def execute_process(
        self,
        request: _m_clappform_data_v1_process_process.ExecuteRequest | None = None,
        *,
        process_id: str | None = None,
        inputs: _m_google_protobuf_struct.Struct | None = None,
        response_mode: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_data_v1_process_process.ExecuteResponse:
        """RPC: /clappform.data.v1.process.ProcessManagement/ExecuteProcess (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("process_id", process_id), ("inputs", inputs), ("response_mode", response_mode),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_data_v1_process_process.ExecuteRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.data.v1.process.ProcessManagement/ExecuteProcess",
            _request,
            _m_clappform_data_v1_process_process.ExecuteRequest,
            _m_clappform_data_v1_process_process.ExecuteResponse,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def get_job_status(
        self,
        request: _m_clappform_data_v1_process_process.GetJobRequest | None = None,
        *,
        job_id: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_data_v1_process_process.JobStatus:
        """RPC: /clappform.data.v1.process.ProcessManagement/GetJobStatus (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("job_id", job_id),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_data_v1_process_process.GetJobRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.data.v1.process.ProcessManagement/GetJobStatus",
            _request,
            _m_clappform_data_v1_process_process.GetJobRequest,
            _m_clappform_data_v1_process_process.JobStatus,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def dismiss_job(
        self,
        request: _m_clappform_data_v1_process_process.DismissJobRequest | None = None,
        *,
        job_id: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_data_v1_process_process.JobStatus:
        """RPC: /clappform.data.v1.process.ProcessManagement/DismissJob (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("job_id", job_id),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_data_v1_process_process.DismissJobRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.data.v1.process.ProcessManagement/DismissJob",
            _request,
            _m_clappform_data_v1_process_process.DismissJobRequest,
            _m_clappform_data_v1_process_process.JobStatus,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def get_job_results(
        self,
        request: _m_clappform_data_v1_process_process.GetJobRequest | None = None,
        *,
        job_id: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_data_v1_process_process.JobResults:
        """RPC: /clappform.data.v1.process.ProcessManagement/GetJobResults (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("job_id", job_id),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_data_v1_process_process.GetJobRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.data.v1.process.ProcessManagement/GetJobResults",
            _request,
            _m_clappform_data_v1_process_process.GetJobRequest,
            _m_clappform_data_v1_process_process.JobResults,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )


class SyncManagement(_runtime.ServiceBase):
    """Wrapper for clappform.data.v1.sync.SyncManagement."""

    def sync_many_by_field(
        self,
        requests: Iterable[_m_clappform_data_v1_sync_sync.SyncRequestByField],
        *,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_data_v1_sync_sync.SyncResponse:
        """RPC: /clappform.data.v1.sync.SyncManagement/SyncManyByField (stream-unary)"""
        _requests = _runtime.ensure_iterable(requests, _m_clappform_data_v1_sync_sync.SyncRequestByField)
        return self._caller.invoke(
            "stream_unary",
            "/clappform.data.v1.sync.SyncManagement/SyncManyByField",
            _requests,
            _m_clappform_data_v1_sync_sync.SyncRequestByField,
            _m_clappform_data_v1_sync_sync.SyncResponse,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )


class UpdateManagement(_runtime.ServiceBase):
    """Wrapper for clappform.data.v1.update.UpdateManagement."""

    def replace_many(
        self,
        request: _m_clappform_data_v1_update_update.UpdateRequestByOid | None = None,
        *,
        data: bytes | None = None,
        collection: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_data_v1_update_update.UpdateRequest:
        """Consider migrating to client streaming RPC

        RPC: /clappform.data.v1.update.UpdateManagement/ReplaceMany (unary-unary)
        """
        _provided = {_k: _v for _k, _v in (("data", data), ("collection", collection),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_data_v1_update_update.UpdateRequestByOid, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.data.v1.update.UpdateManagement/ReplaceMany",
            _request,
            _m_clappform_data_v1_update_update.UpdateRequestByOid,
            _m_clappform_data_v1_update_update.UpdateRequest,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def replace_many_by_field(
        self,
        requests: Iterable[_m_clappform_data_v1_update_update.UpdateRequestByField],
        *,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_data_v1_update_update.UpdateRequestResponse:
        """RPC: /clappform.data.v1.update.UpdateManagement/ReplaceManyByField (stream-unary)"""
        _requests = _runtime.ensure_iterable(requests, _m_clappform_data_v1_update_update.UpdateRequestByField)
        return self._caller.invoke(
            "stream_unary",
            "/clappform.data.v1.update.UpdateManagement/ReplaceManyByField",
            _requests,
            _m_clappform_data_v1_update_update.UpdateRequestByField,
            _m_clappform_data_v1_update_update.UpdateRequestResponse,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def replace_many_by_query(
        self,
        request: _m_clappform_data_v1_update_update.UpdateRequestByQuery | None = None,
        *,
        set_values: bytes | None = None,
        collection: str | None = None,
        query: bytes | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_data_v1_update_update.UpdateRequestResponse:
        """RPC: /clappform.data.v1.update.UpdateManagement/ReplaceManyByQuery (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("set_values", set_values), ("collection", collection), ("query", query),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_data_v1_update_update.UpdateRequestByQuery, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.data.v1.update.UpdateManagement/ReplaceManyByQuery",
            _request,
            _m_clappform_data_v1_update_update.UpdateRequestByQuery,
            _m_clappform_data_v1_update_update.UpdateRequestResponse,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def update_many(
        self,
        requests: Iterable[_m_clappform_data_v1_update_update.UpdateRequestByOid],
        *,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_data_v1_update_update.UpdateRequestResponse:
        """RPC: /clappform.data.v1.update.UpdateManagement/UpdateMany (stream-unary)"""
        _requests = _runtime.ensure_iterable(requests, _m_clappform_data_v1_update_update.UpdateRequestByOid)
        return self._caller.invoke(
            "stream_unary",
            "/clappform.data.v1.update.UpdateManagement/UpdateMany",
            _requests,
            _m_clappform_data_v1_update_update.UpdateRequestByOid,
            _m_clappform_data_v1_update_update.UpdateRequestResponse,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def update_many_by_field(
        self,
        requests: Iterable[_m_clappform_data_v1_update_update.UpdateRequestByField],
        *,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_data_v1_update_update.UpdateRequestResponse:
        """RPC: /clappform.data.v1.update.UpdateManagement/UpdateManyByField (stream-unary)"""
        _requests = _runtime.ensure_iterable(requests, _m_clappform_data_v1_update_update.UpdateRequestByField)
        return self._caller.invoke(
            "stream_unary",
            "/clappform.data.v1.update.UpdateManagement/UpdateManyByField",
            _requests,
            _m_clappform_data_v1_update_update.UpdateRequestByField,
            _m_clappform_data_v1_update_update.UpdateRequestResponse,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def update_many_by_query(
        self,
        request: _m_clappform_data_v1_update_update.UpdateRequestByQuery | None = None,
        *,
        set_values: bytes | None = None,
        collection: str | None = None,
        query: bytes | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_data_v1_update_update.UpdateRequestResponse:
        """RPC: /clappform.data.v1.update.UpdateManagement/UpdateManyByQuery (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("set_values", set_values), ("collection", collection), ("query", query),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_data_v1_update_update.UpdateRequestByQuery, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.data.v1.update.UpdateManagement/UpdateManyByQuery",
            _request,
            _m_clappform_data_v1_update_update.UpdateRequestByQuery,
            _m_clappform_data_v1_update_update.UpdateRequestResponse,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )


class DataAPI:
    """Generated sub-client for the data API."""

    def __init__(self, caller: _runtime.Caller) -> None:
        self.aggregate = AggregateManagement(caller)
        self.change_request = ChangeRequestManagement(caller)
        self.chat = ChatManagement(caller)
        self.delete = DeleteManagement(caller)
        self.general = GeneralManagement(caller)
        self.index = IndexManagement(caller)
        self.insert = InsertManagement(caller)
        self.process = ProcessManagement(caller)
        self.sync = SyncManagement(caller)
        self.update = UpdateManagement(caller)
