"""Generated by tools/generate.py — do not edit."""

from __future__ import annotations

from collections.abc import Iterable, Iterator, Sequence
from typing import Any

from clappform import _runtime
import clappform.gen.clappform.notifier.v1.health.health_pb2 as _m_clappform_notifier_v1_health_health
import clappform.gen.clappform.notifier.v1.inbox.inbox_pb2 as _m_clappform_notifier_v1_inbox_inbox
import clappform.gen.clappform.notifier.v1.outbound.outbound_pb2 as _m_clappform_notifier_v1_outbound_outbound
import clappform.gen.clappform.notifier.v1.whatsapp.whatsapp_pb2 as _m_clappform_notifier_v1_whatsapp_whatsapp
import clappform.gen.clappform.v1.commons.commons_pb2 as _m_clappform_v1_commons_commons


class GeneralManagement(_runtime.ServiceBase):
    """Wrapper for clappform.notifier.v1.general.GeneralManagement."""

    def general(
        self,
        request: _m_clappform_v1_commons_commons.Empty | None = None,
        *,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_v1_commons_commons.Message:
        """RPC: /clappform.notifier.v1.general.GeneralManagement/General (unary-unary)"""
        _provided: dict[str, Any] = {}
        _request = _runtime.build_request(_m_clappform_v1_commons_commons.Empty, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.notifier.v1.general.GeneralManagement/General",
            _request,
            _m_clappform_v1_commons_commons.Empty,
            _m_clappform_v1_commons_commons.Message,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )


class HealthManagement(_runtime.ServiceBase):
    """Wrapper for clappform.notifier.v1.health.HealthManagement."""

    def health(
        self,
        request: _m_clappform_v1_commons_commons.Empty | None = None,
        *,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_notifier_v1_health_health.HealthStatus:
        """RPC: /clappform.notifier.v1.health.HealthManagement/Health (unary-unary)"""
        _provided: dict[str, Any] = {}
        _request = _runtime.build_request(_m_clappform_v1_commons_commons.Empty, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.notifier.v1.health.HealthManagement/Health",
            _request,
            _m_clappform_v1_commons_commons.Empty,
            _m_clappform_notifier_v1_health_health.HealthStatus,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )


class InboxManagement(_runtime.ServiceBase):
    """Wrapper for clappform.notifier.v1.inbox.InboxManagement."""

    def stream_messages(
        self,
        request: _m_clappform_notifier_v1_inbox_inbox.GetMessagesRequest | None = None,
        *,
        user_id: str | None = None,
        status: Sequence[int] | None = None,
        level: Sequence[int] | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> Iterator[_m_clappform_notifier_v1_inbox_inbox.Message]:
        """RPC: /clappform.notifier.v1.inbox.InboxManagement/StreamMessages (unary-stream)"""
        _provided = {_k: _v for _k, _v in (("user_id", user_id), ("status", status), ("level", level),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_notifier_v1_inbox_inbox.GetMessagesRequest, request, _provided)
        return self._caller.invoke(
            "unary_stream",
            "/clappform.notifier.v1.inbox.InboxManagement/StreamMessages",
            _request,
            _m_clappform_notifier_v1_inbox_inbox.GetMessagesRequest,
            _m_clappform_notifier_v1_inbox_inbox.Message,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def get_messages(
        self,
        request: _m_clappform_notifier_v1_inbox_inbox.GetMessagesRequest | None = None,
        *,
        user_id: str | None = None,
        status: Sequence[int] | None = None,
        level: Sequence[int] | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_notifier_v1_inbox_inbox.Messages:
        """RPC: /clappform.notifier.v1.inbox.InboxManagement/GetMessages (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("user_id", user_id), ("status", status), ("level", level),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_notifier_v1_inbox_inbox.GetMessagesRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.notifier.v1.inbox.InboxManagement/GetMessages",
            _request,
            _m_clappform_notifier_v1_inbox_inbox.GetMessagesRequest,
            _m_clappform_notifier_v1_inbox_inbox.Messages,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def send_message(
        self,
        request: _m_clappform_notifier_v1_inbox_inbox.MessageRequest | None = None,
        *,
        level: int | None = None,
        status: int | None = None,
        message: str | None = None,
        user_ids: Sequence[str] | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_v1_commons_commons.Message:
        """RPC: /clappform.notifier.v1.inbox.InboxManagement/SendMessage (unary-unary)
        Fields only settable via a request message (name collision): metadata
        """
        _provided = {_k: _v for _k, _v in (("level", level), ("status", status), ("message", message), ("user_ids", user_ids),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_notifier_v1_inbox_inbox.MessageRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.notifier.v1.inbox.InboxManagement/SendMessage",
            _request,
            _m_clappform_notifier_v1_inbox_inbox.MessageRequest,
            _m_clappform_v1_commons_commons.Message,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def set_status(
        self,
        request: _m_clappform_notifier_v1_inbox_inbox.SetStatusRequest | None = None,
        *,
        status: int | None = None,
        ids: Sequence[str] | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_notifier_v1_inbox_inbox.Messages:
        """RPC: /clappform.notifier.v1.inbox.InboxManagement/SetStatus (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("status", status), ("ids", ids),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_notifier_v1_inbox_inbox.SetStatusRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.notifier.v1.inbox.InboxManagement/SetStatus",
            _request,
            _m_clappform_notifier_v1_inbox_inbox.SetStatusRequest,
            _m_clappform_notifier_v1_inbox_inbox.Messages,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )


class OutboundManagement(_runtime.ServiceBase):
    """Wrapper for clappform.notifier.v1.outbound.OutboundManagement."""

    def send_message(
        self,
        request: _m_clappform_notifier_v1_outbound_outbound.Messages | None = None,
        *,
        messages: Sequence[_m_clappform_notifier_v1_outbound_outbound.Message] | None = None,
        pagination: _m_clappform_v1_commons_commons.Pagination | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_notifier_v1_outbound_outbound.MessageResponse:
        """RPC: /clappform.notifier.v1.outbound.OutboundManagement/SendMessage (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("messages", messages), ("pagination", pagination),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_notifier_v1_outbound_outbound.Messages, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.notifier.v1.outbound.OutboundManagement/SendMessage",
            _request,
            _m_clappform_notifier_v1_outbound_outbound.Messages,
            _m_clappform_notifier_v1_outbound_outbound.MessageResponse,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )


class WhatsappManagement(_runtime.ServiceBase):
    """Wrapper for clappform.notifier.v1.whatsapp.WhatsappManagement."""

    def send_message(
        self,
        request: _m_clappform_notifier_v1_whatsapp_whatsapp.MessageRequest | None = None,
        *,
        phone_number: str | None = None,
        message: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_notifier_v1_whatsapp_whatsapp.MessageResponse:
        """RPC: /clappform.notifier.v1.whatsapp.WhatsappManagement/SendMessage (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("phone_number", phone_number), ("message", message),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_notifier_v1_whatsapp_whatsapp.MessageRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.notifier.v1.whatsapp.WhatsappManagement/SendMessage",
            _request,
            _m_clappform_notifier_v1_whatsapp_whatsapp.MessageRequest,
            _m_clappform_notifier_v1_whatsapp_whatsapp.MessageResponse,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def send_template(
        self,
        request: _m_clappform_notifier_v1_whatsapp_whatsapp.TemplateRequest | None = None,
        *,
        phone_number: str | None = None,
        template_name: str | None = None,
        language_code: str | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_notifier_v1_whatsapp_whatsapp.HealthStatus:
        """RPC: /clappform.notifier.v1.whatsapp.WhatsappManagement/SendTemplate (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("phone_number", phone_number), ("template_name", template_name), ("language_code", language_code),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_notifier_v1_whatsapp_whatsapp.TemplateRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.notifier.v1.whatsapp.WhatsappManagement/SendTemplate",
            _request,
            _m_clappform_notifier_v1_whatsapp_whatsapp.TemplateRequest,
            _m_clappform_notifier_v1_whatsapp_whatsapp.HealthStatus,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def webhook_event(
        self,
        request: _m_clappform_notifier_v1_whatsapp_whatsapp.WebhookEventRequest | None = None,
        *,
        object: str | None = None,
        entry: Sequence[_m_clappform_notifier_v1_whatsapp_whatsapp.WebhookEntry] | None = None,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_notifier_v1_whatsapp_whatsapp.WebhookEventResponse:
        """RPC: /clappform.notifier.v1.whatsapp.WhatsappManagement/WebhookEvent (unary-unary)"""
        _provided = {_k: _v for _k, _v in (("object", object), ("entry", entry),) if _v is not None}
        _request = _runtime.build_request(_m_clappform_notifier_v1_whatsapp_whatsapp.WebhookEventRequest, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.notifier.v1.whatsapp.WhatsappManagement/WebhookEvent",
            _request,
            _m_clappform_notifier_v1_whatsapp_whatsapp.WebhookEventRequest,
            _m_clappform_notifier_v1_whatsapp_whatsapp.WebhookEventResponse,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )

    def webhook_verification(
        self,
        request: _m_clappform_v1_commons_commons.Empty | None = None,
        *,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str], ...] | None = None,
        location: str | None = None,
    ) -> _m_clappform_notifier_v1_whatsapp_whatsapp.WebhookVerifyResponse:
        """RPC: /clappform.notifier.v1.whatsapp.WhatsappManagement/WebhookVerification (unary-unary)"""
        _provided: dict[str, Any] = {}
        _request = _runtime.build_request(_m_clappform_v1_commons_commons.Empty, request, _provided)
        return self._caller.invoke(
            "unary_unary",
            "/clappform.notifier.v1.whatsapp.WhatsappManagement/WebhookVerification",
            _request,
            _m_clappform_v1_commons_commons.Empty,
            _m_clappform_notifier_v1_whatsapp_whatsapp.WebhookVerifyResponse,
            timeout=timeout,
            metadata=metadata,
            location=location,
        )


class NotifierAPI:
    """Generated sub-client for the notifier API."""

    def __init__(self, caller: _runtime.Caller) -> None:
        self.general = GeneralManagement(caller)
        self.health = HealthManagement(caller)
        self.inbox = InboxManagement(caller)
        self.outbound = OutboundManagement(caller)
        self.whatsapp = WhatsappManagement(caller)
