"""Regenerate clappform/gen and clappform/services from the commons protos.

Reads the commons tag pinned in COMMONS_VERSION, exports the proto tree from a
local commons clone at exactly that ref (``git archive``, so the working tree
state of the clone never leaks in), compiles it with grpc_tools.protoc, and
rewrites imports so the generated modules are self-contained under
``clappform.gen``. Finally invokes servicegen to emit the ergonomic service
layer under ``clappform.services``.

Usage:
    python tools/generate.py

The commons clone is located via the CLAPPFORM_COMMONS_DIR environment
variable, falling back to a sibling ``../commons`` checkout.
"""

from __future__ import annotations

import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
GEN_DIR = REPO_ROOT / "src" / "clappform" / "gen"
SERVICES_DIR = REPO_ROOT / "src" / "clappform" / "services"
PROTO_ROOT = "protobufs"

# Proto paths never generated:
# - google/protobuf/** ships with the protobuf runtime
# - clappform/nbflow/** is internal-only
EXCLUDED_PREFIXES = ("google/protobuf/", "clappform/nbflow/")

GENERATED_HEADER = '"""Generated by tools/generate.py — do not edit."""\n'


def read_pin() -> str:
    return (REPO_ROOT / "COMMONS_VERSION").read_text(encoding="utf-8").strip()


def commons_dir() -> Path:
    override = os.environ.get("CLAPPFORM_COMMONS_DIR")
    candidate = Path(override) if override else REPO_ROOT.parent / "commons"
    if not (candidate / ".git").exists():
        raise SystemExit(
            f"commons clone not found at {candidate}; set CLAPPFORM_COMMONS_DIR"
        )
    return candidate


def export_protos(commons: Path, ref: str, staging: Path) -> Path:
    """Export <commons>/protobufs at *ref* into *staging* via git archive."""
    archive = staging / "protos.tar"
    with archive.open("wb") as fh:
        subprocess.run(
            ["git", "-C", str(commons), "archive", "--format=tar", ref, PROTO_ROOT],
            check=True,
            stdout=fh,
        )
    subprocess.run(
        ["tar", "-xf", str(archive), "-C", str(staging)],
        check=True,
    )
    return staging / PROTO_ROOT


def collect_protos(proto_root: Path) -> list[str]:
    files = []
    for path in sorted(proto_root.rglob("*.proto")):
        rel = path.relative_to(proto_root).as_posix()
        if rel.startswith(EXCLUDED_PREFIXES):
            continue
        files.append(rel)
    if not files:
        raise SystemExit(f"no protos found under {proto_root}")
    return files


def run_protoc(proto_root: Path, protos: list[str], descriptor_out: Path) -> None:
    if GEN_DIR.exists():
        shutil.rmtree(GEN_DIR)
    GEN_DIR.mkdir(parents=True)
    args = [
        sys.executable,
        "-m",
        "grpc_tools.protoc",
        f"-I{proto_root}",
        f"--python_out={GEN_DIR}",
        f"--pyi_out={GEN_DIR}",
        f"--grpc_python_out={GEN_DIR}",
        f"--descriptor_set_out={descriptor_out}",
        "--include_imports",
        "--include_source_info",
        *protos,
    ]
    subprocess.run(args, check=True, cwd=proto_root)


# Import-path prefixes that must be renested under clappform.gen. Never
# touches google.protobuf (protobuf runtime) or plain grpc (grpcio runtime).
_PREFIX = r"(clappform|google\.api|grpc\.gateway)"
_FROM_IMPORT = re.compile(rf"^from {_PREFIX}((?:\.\w+)*) import ", flags=re.MULTILINE)
_PLAIN_IMPORT = re.compile(rf"^import {_PREFIX}((?:\.\w+)*)$", flags=re.MULTILINE)
# Dotted references in .pyi bodies (safe there: no serialized descriptors).
_DOTTED_REF = re.compile(rf"(?<![\w.]){_PREFIX}(?!\.gen\.)\.")


def rewrite_imports() -> None:
    for path in GEN_DIR.rglob("*.py"):
        text = path.read_text(encoding="utf-8")
        text = _FROM_IMPORT.sub(r"from clappform.gen.\1\2 import ", text)
        path.write_text(text, encoding="utf-8", newline="\n")
    for path in GEN_DIR.rglob("*.pyi"):
        text = path.read_text(encoding="utf-8")
        text = _FROM_IMPORT.sub(r"from clappform.gen.\1\2 import ", text)
        text = _PLAIN_IMPORT.sub(r"import clappform.gen.\1\2", text)
        text = _DOTTED_REF.sub(r"clappform.gen.\1.", text)
        path.write_text(text, encoding="utf-8", newline="\n")


def create_inits() -> None:
    for directory in [GEN_DIR, *(p for p in GEN_DIR.rglob("*") if p.is_dir())]:
        init = directory / "__init__.py"
        if not init.exists():
            init.write_text(GENERATED_HEADER, encoding="utf-8", newline="\n")


def write_proto_version(ref: str) -> None:
    (REPO_ROOT / "src" / "clappform" / "_proto_version.py").write_text(
        '"""Written by tools/generate.py — do not edit by hand."""\n'
        "\n"
        f'__proto_version__ = "{ref}"\n',
        encoding="utf-8",
        newline="\n",
    )


def main() -> None:
    ref = read_pin()
    commons = commons_dir()
    print(f"generating from commons @ {ref} ({commons})")
    with tempfile.TemporaryDirectory() as tmp:
        staging = Path(tmp)
        proto_root = export_protos(commons, ref, staging)
        protos = collect_protos(proto_root)
        descriptor_out = staging / "descriptors.binpb"
        run_protoc(proto_root, protos, descriptor_out)
        rewrite_imports()
        create_inits()
        write_proto_version(ref)

        sys.path.insert(0, str(Path(__file__).resolve().parent))
        import servicegen

        servicegen.generate(descriptor_out.read_bytes(), SERVICES_DIR)
    print(f"generated {sum(1 for _ in GEN_DIR.rglob('*.py'))} modules in clappform/gen")


if __name__ == "__main__":
    main()
