"""Generate the ergonomic service layer from a compiled FileDescriptorSet.

For every Clappform API family (``clappform.<family>.v1``) this emits one
module under ``clappform/services/`` containing:

- one family class (``DataAPI``, ``ClientAPI``, ...) with an attribute per
  proto service (``InsertManagement`` -> ``.insert``),
- one wrapper class per service with a snake_case method per RPC,
- flattened keyword arguments mirroring the request message fields (a
  prebuilt request message is always accepted as the first positional
  argument instead),
- streaming adapters: stream-input methods take an iterable of requests,
  stream-output methods return an iterator of responses,
- an ``iter_<rpc>`` auto-pagination variant for RPCs that take
  ``clappform.v1.commons.PaginationRequest`` and return a message carrying
  ``clappform.v1.commons.Pagination`` plus a repeated item field,
- docstrings sourced from the proto comments.

Generated methods never import grpc: they call ``Caller.invoke`` from
``clappform._runtime``, which the transport (or a test double) implements.

The generator has no per-service configuration. It keys only on the two
commons pagination message names and a family-alias map.
"""

from __future__ import annotations

import keyword
import re
from pathlib import Path

from google.protobuf import descriptor_pb2

FAMILY_ALIASES = {"authoriser": "auth"}
RESERVED_PARAMS = frozenset({"self", "request", "requests", "timeout", "metadata", "location"})
PAGINATION_REQUEST = ".clappform.v1.commons.PaginationRequest"
PAGINATION_MESSAGE = ".clappform.v1.commons.Pagination"
PB2_IMPORT_PREFIX = "clappform.gen."

HEADER = '"""Generated by tools/generate.py. Do not edit."""\n'

_F = descriptor_pb2.FieldDescriptorProto
_SCALAR_TYPES: dict[int, str] = {
    _F.TYPE_DOUBLE: "float",
    _F.TYPE_FLOAT: "float",
    _F.TYPE_INT64: "int",
    _F.TYPE_UINT64: "int",
    _F.TYPE_INT32: "int",
    _F.TYPE_FIXED64: "int",
    _F.TYPE_FIXED32: "int",
    _F.TYPE_BOOL: "bool",
    _F.TYPE_STRING: "str",
    _F.TYPE_GROUP: "Any",
    _F.TYPE_BYTES: "bytes",
    _F.TYPE_UINT32: "int",
    _F.TYPE_ENUM: "int",
    _F.TYPE_SFIXED32: "int",
    _F.TYPE_SFIXED64: "int",
    _F.TYPE_SINT32: "int",
    _F.TYPE_SINT64: "int",
}


def snake_case(name: str) -> str:
    s = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", name)
    return re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s).lower()


def _pb2_module(proto_path: str) -> str:
    """clappform/data/v1/insert/insert.proto -> clappform.gen....insert_pb2"""
    dotted = proto_path[: -len(".proto")].replace("/", ".")
    if proto_path.startswith("google/protobuf/"):
        return f"{dotted}_pb2"  # well-known types ship with the protobuf runtime
    return f"{PB2_IMPORT_PREFIX}{dotted}_pb2"


def _pb2_alias(proto_path: str) -> str:
    return "_m_" + re.sub(r"\W", "_", proto_path[: -len(".proto")])


class _Index:
    """Message and comment lookups across the whole descriptor set."""

    def __init__(self, fds: descriptor_pb2.FileDescriptorSet) -> None:
        self.files = list(fds.file)
        # ".pkg.Msg[.Nested]" -> (message descriptor, owning file)
        self.messages: dict[
            str, tuple[descriptor_pb2.DescriptorProto, descriptor_pb2.FileDescriptorProto]
        ] = {}
        for file in self.files:
            prefix = f".{file.package}" if file.package else ""
            for message in file.message_type:
                self._register(message, prefix, file)

    def _register(
        self,
        message: descriptor_pb2.DescriptorProto,
        prefix: str,
        file: descriptor_pb2.FileDescriptorProto,
    ) -> None:
        full = f"{prefix}.{message.name}"
        self.messages[full] = (message, file)
        for nested in message.nested_type:
            self._register(nested, full, file)

    def message(self, type_name: str) -> descriptor_pb2.DescriptorProto:
        return self.messages[type_name][0]

    def owning_file(self, type_name: str) -> descriptor_pb2.FileDescriptorProto:
        return self.messages[type_name][1]

    def class_ref(self, type_name: str) -> str:
        """Python reference for a message type, via its pb2 module alias."""
        message, file = self.messages[type_name]
        package_prefix = f".{file.package}." if file.package else "."
        class_path = type_name[len(package_prefix):]
        return f"{_pb2_alias(file.name)}.{class_path}"


def _method_comment(
    file: descriptor_pb2.FileDescriptorProto, service_idx: int, method_idx: int
) -> str:
    for location in file.source_code_info.location:
        if list(location.path) == [6, service_idx, 2, method_idx]:
            return location.leading_comments.strip()
    return ""


def _clean_docstring(text: str) -> str:
    return text.replace('"""', "'''").replace("\\", "\\\\").strip()


def _annotation(field: descriptor_pb2.FieldDescriptorProto, index: _Index) -> str:
    if field.type == _F.TYPE_MESSAGE:
        entry = index.message(field.type_name)
        if entry.options.map_entry:
            key = _annotation(entry.field[0], index)
            value = _annotation(entry.field[1], index)
            return f"dict[{key}, {value}]"
        base = index.class_ref(field.type_name)
    else:
        base = _SCALAR_TYPES.get(field.type, "Any")
    if field.label == _F.LABEL_REPEATED:
        return f"Sequence[{base}]"
    return base


class _MethodPlan:
    def __init__(
        self,
        file: descriptor_pb2.FileDescriptorProto,
        service_idx: int,
        method_idx: int,
        method: descriptor_pb2.MethodDescriptorProto,
        index: _Index,
    ) -> None:
        self.method = method
        self.name = snake_case(method.name)
        self.comment = _method_comment(file, service_idx, method_idx)
        self.input_type = method.input_type
        self.output_type = method.output_type
        self.client_streaming = method.client_streaming
        self.server_streaming = method.server_streaming
        self.kind = (
            f"{'stream' if method.client_streaming else 'unary'}_"
            f"{'stream' if method.server_streaming else 'unary'}"
        )
        self.full_method = f"/{file.package}.{file.service[service_idx].name}/{method.name}"

        self.flattened: list[descriptor_pb2.FieldDescriptorProto] = []
        self.skipped_fields: list[str] = []
        if not method.client_streaming:
            for field in index.message(method.input_type).field:
                if field.name in RESERVED_PARAMS or keyword.iskeyword(field.name):
                    self.skipped_fields.append(field.name)
                else:
                    self.flattened.append(field)

        self.pagination = self._pagination_plan(index)

    def _pagination_plan(self, index: _Index) -> tuple[str, str, str] | None:
        """(pagination_field, items_field, item_type_ref) or None."""
        if self.client_streaming or self.server_streaming:
            return None
        if self.input_type != PAGINATION_REQUEST:
            return None
        output = index.message(self.output_type)
        pagination_field = next(
            (
                f.name
                for f in output.field
                if f.type == _F.TYPE_MESSAGE and f.type_name == PAGINATION_MESSAGE
            ),
            None,
        )
        if pagination_field is None:
            return None
        items = next(
            (
                f
                for f in output.field
                if f.label == _F.LABEL_REPEATED
                and f.type == _F.TYPE_MESSAGE
                and f.type_name != PAGINATION_MESSAGE
                and not index.message(f.type_name).options.map_entry
            ),
            None,
        )
        if items is None:
            return None
        return pagination_field, items.name, index.class_ref(items.type_name)


def _emit_method(plan: _MethodPlan, index: _Index, out: list[str]) -> None:
    request_ref = index.class_ref(plan.input_type)
    response_ref = index.class_ref(plan.output_type)
    return_ann = f"Iterator[{response_ref}]" if plan.server_streaming else response_ref

    doc_lines = []
    if plan.comment:
        doc_lines.extend(_clean_docstring(plan.comment).splitlines())
        doc_lines.append("")
    doc_lines.append(f"RPC: {plan.full_method} ({plan.kind.replace('_', '-')})")
    if plan.skipped_fields:
        names = ", ".join(sorted(plan.skipped_fields))
        doc_lines.append(
            f"Fields only settable via a request message (name collision): {names}"
        )

    if plan.client_streaming:
        out.append(f"    def {plan.name}(")
        out.append("        self,")
        out.append(f"        requests: Iterable[{request_ref}],")
        out.append("        *,")
        out.append("        timeout: float | None = None,")
        out.append("        metadata: tuple[tuple[str, str], ...] | None = None,")
        out.append("        location: str | None = None,")
        out.append(f"    ) -> {return_ann}:")
        _emit_docstring(doc_lines, out)
        out.append(
            f"        _requests = _runtime.ensure_iterable(requests, {request_ref})"
        )
        out.append("        return self._caller.invoke(")
        out.append(f'            "{plan.kind}",')
        out.append(f'            "{plan.full_method}",')
        out.append("            _requests,")
        out.append(f"            {request_ref},")
        out.append(f"            {response_ref},")
        out.append("            timeout=timeout,")
        out.append("            metadata=metadata,")
        out.append("            location=location,")
        out.append("        )")
        out.append("")
        return

    out.append(f"    def {plan.name}(")
    out.append("        self,")
    out.append(f"        request: {request_ref} | None = None,")
    out.append("        *,")
    for field in plan.flattened:
        out.append(f"        {field.name}: {_annotation(field, index)} | None = None,")
    out.append("        timeout: float | None = None,")
    out.append("        metadata: tuple[tuple[str, str], ...] | None = None,")
    out.append("        location: str | None = None,")
    out.append(f"    ) -> {return_ann}:")
    _emit_docstring(doc_lines, out)
    if plan.flattened:
        pairs = ", ".join(f'("{f.name}", {f.name})' for f in plan.flattened)
        out.append(
            f"        _provided = {{_k: _v for _k, _v in ({pairs},) if _v is not None}}"
        )
    else:
        out.append("        _provided: dict[str, Any] = {}")
    out.append(
        f"        _request = _runtime.build_request({request_ref}, request, _provided)"
    )
    out.append("        return self._caller.invoke(")
    out.append(f'            "{plan.kind}",')
    out.append(f'            "{plan.full_method}",')
    out.append("            _request,")
    out.append(f"            {request_ref},")
    out.append(f"            {response_ref},")
    out.append("            timeout=timeout,")
    out.append("            metadata=metadata,")
    out.append("            location=location,")
    out.append("        )")
    out.append("")

    if plan.pagination is not None:
        _emit_pagination(plan, index, out)


def _emit_pagination(plan: _MethodPlan, index: _Index, out: list[str]) -> None:
    # Narrowing for mypy: callers only reach this for a plan with pagination.
    assert plan.pagination is not None  # noqa: S101
    pagination_field, items_field, item_ref = plan.pagination
    fields = [f for f in plan.flattened if f.name != "page"]
    out.append(f"    def iter_{plan.name}(")
    out.append("        self,")
    out.append("        *,")
    for field in fields:
        out.append(f"        {field.name}: {_annotation(field, index)} | None = None,")
    out.append("        timeout: float | None = None,")
    out.append("        metadata: tuple[tuple[str, str], ...] | None = None,")
    out.append("        location: str | None = None,")
    out.append(f"    ) -> Iterator[{item_ref}]:")
    doc = [
        f"Auto-paginating variant of ``{plan.name}``.",
        "",
        f"Yields each item from ``{items_field}`` across all pages, following",
        f"``{pagination_field}`` until the last page.",
    ]
    _emit_docstring(doc, out)
    out.append("        _page = 1")
    out.append("        while True:")
    args = ["page=_page"]
    args += [f"{f.name}={f.name}" for f in fields]
    args += ["timeout=timeout", "metadata=metadata", "location=location"]
    out.append(f"            _resp = self.{plan.name}({', '.join(args)})")
    out.append(f"            yield from _resp.{items_field}")
    out.append(f"            _pagination = _resp.{pagination_field}")
    out.append("            if _pagination.pages <= _pagination.page:")
    out.append("                break")
    out.append("            _page = _pagination.page + 1")
    out.append("")


def _emit_docstring(lines: list[str], out: list[str]) -> None:
    if len(lines) == 1:
        out.append(f'        """{lines[0]}"""')
        return
    out.append('        """' + lines[0])
    out.extend(f"        {line}".rstrip() for line in lines[1:])
    out.append('        """')


def _service_attr(service_name: str, taken: set[str], package: str) -> str:
    base = service_name.removesuffix("Management") or service_name
    attr = snake_case(base)
    if attr in taken:
        attr = f"{attr}_{package.rsplit('.', 1)[-1]}"
    if attr in taken:
        raise ValueError(f"cannot derive unique attribute for service {service_name}")
    return attr


def _family_of(package: str) -> str | None:
    parts = package.split(".")
    if len(parts) < 3 or parts[0] != "clappform":
        return None
    if parts[1].startswith("v") and parts[1][1:].isdigit():
        return None  # clappform.v1.commons: shared types, no services
    return parts[1]


def _render_service(
    file: descriptor_pb2.FileDescriptorProto,
    service_idx: int,
    service: descriptor_pb2.ServiceDescriptorProto,
    index: _Index,
    taken: set[str],
) -> tuple[str, str, set[str]]:
    """Return (class source, family attribute name, pb2 modules to import)."""
    plans = [
        _MethodPlan(file, service_idx, method_idx, method, index)
        for method_idx, method in enumerate(service.method)
    ]

    # Collect the pb2 modules this service touches, for imports. A pagination
    # plan's item type needs no separate entry, since it is a field of the
    # output message, whose file is added here.
    pb2_paths: set[str] = set()
    for plan in plans:
        pb2_paths.add(index.owning_file(plan.input_type).name)
        pb2_paths.add(index.owning_file(plan.output_type).name)
        for field in plan.flattened:
            if field.type == _F.TYPE_MESSAGE and not index.message(
                field.type_name
            ).options.map_entry:
                pb2_paths.add(index.owning_file(field.type_name).name)

    out: list[str] = []
    out.append(f"class {service.name}(_runtime.ServiceBase):")
    out.append(f'    """Wrapper for {file.package}.{service.name}."""')
    out.append("")
    for plan in plans:
        _emit_method(plan, index, out)

    attr = _service_attr(service.name, taken, file.package)
    return "\n".join(out).rstrip() + "\n", attr, pb2_paths


def _render_family(
    family: str,
    files: list[descriptor_pb2.FileDescriptorProto],
    index: _Index,
) -> tuple[str, str, str]:
    """Return (module alias, family class name, module source) for one family."""
    alias = FAMILY_ALIASES.get(family, family)
    class_name = f"{alias.capitalize()}API"

    pb2_paths: set[str] = set()
    service_blocks: list[str] = []
    wiring: list[tuple[str, str]] = []  # (attr, service class)
    taken: set[str] = set()

    for file in sorted(files, key=lambda f: f.name):
        for service_idx, service in enumerate(file.service):
            block, attr, paths = _render_service(file, service_idx, service, index, taken)
            service_blocks.append(block)
            pb2_paths |= paths
            taken.add(attr)
            wiring.append((attr, service.name))

    module_lines = [HEADER]
    module_lines.append("from __future__ import annotations")
    module_lines.append("")
    module_lines.append("from collections.abc import Iterable, Iterator, Sequence")
    module_lines.append("from typing import Any")
    module_lines.append("")
    module_lines.append("from clappform import _runtime")
    for path in sorted(pb2_paths):
        module_lines.append(f"import {_pb2_module(path)} as {_pb2_alias(path)}")
    module_lines.append("")
    module_lines.append("")
    for block in service_blocks:
        module_lines.append(block)
        module_lines.append("")
    module_lines.append(f"class {class_name}:")
    module_lines.append(f'    """Generated sub-client for the {family} API."""')
    module_lines.append("")
    module_lines.append("    def __init__(self, caller: _runtime.Caller) -> None:")
    for attr, service_class in wiring:
        module_lines.append(f"        self.{attr} = {service_class}(caller)")
    module_lines.append("")
    return alias, class_name, "\n".join(module_lines)


def _render_init(registry: list[tuple[str, str, str]]) -> str:
    """Return the services package __init__, given (alias, class, module) rows."""
    init_lines = [HEADER]
    init_lines.append("from __future__ import annotations")
    init_lines.append("")
    for _alias, class_name, module in registry:
        init_lines.append(f"from clappform.services.{module} import {class_name}")
    init_lines.append("")
    init_lines.append("API_FAMILIES: dict[str, type] = {")
    for alias, class_name, _module in registry:
        init_lines.append(f'    "{alias}": {class_name},')
    init_lines.append("}")
    init_lines.append("")
    init_lines.append(
        "__all__ = [\"API_FAMILIES\", "
        + ", ".join(f'"{class_name}"' for _a, class_name, _m in registry)
        + "]"
    )
    init_lines.append("")
    return "\n".join(init_lines)


def generate_sources(descriptor_set: bytes) -> dict[str, str]:
    """Return {module filename: source} for the full service layer."""
    fds = descriptor_pb2.FileDescriptorSet()
    fds.MergeFromString(descriptor_set)
    index = _Index(fds)

    families: dict[str, list[descriptor_pb2.FileDescriptorProto]] = {}
    for file in fds.file:
        family = _family_of(file.package)
        if family is not None and file.service:
            families.setdefault(family, []).append(file)

    sources: dict[str, str] = {}
    registry: list[tuple[str, str, str]] = []  # (attr, class, module)
    for family in sorted(families):
        alias, class_name, source = _render_family(family, families[family], index)
        sources[f"{alias}.py"] = source
        registry.append((alias, class_name, alias))

    sources["__init__.py"] = _render_init(registry)
    return sources


def generate(descriptor_set: bytes, out_dir: Path) -> None:
    sources = generate_sources(descriptor_set)
    if out_dir.exists():
        for existing in out_dir.glob("*.py"):
            existing.unlink()
    out_dir.mkdir(parents=True, exist_ok=True)
    for filename, source in sources.items():
        (out_dir / filename).write_text(source, encoding="utf-8", newline="\n")
