"""Generate the ergonomic service layer from a compiled FileDescriptorSet.

For every Clappform API family (``clappform.<family>.v1``) this emits one
module under ``clappform/services/`` containing:

- one family class (``DataAPI``, ``ClientAPI``, ...) with an attribute per
  proto service (``InsertManagement`` -> ``.insert``),
- one wrapper class per service with a snake_case method per RPC,
- flattened keyword arguments mirroring the request message fields (a
  prebuilt request message is always accepted as the first positional
  argument instead),
- streaming adapters: stream-input methods take an iterable of requests,
  stream-output methods return an iterator of responses,
- an ``iter_<rpc>`` auto-pagination variant for RPCs that take
  ``clappform.v1.commons.PaginationRequest`` and return a message carrying
  ``clappform.v1.commons.Pagination`` plus a repeated item field,
- docstrings sourced from the proto comments, falling back to the
  grpc-gateway ``openapiv2_operation`` summary and description.

A request field named like a per-call argument (``timeout``, ``metadata``,
``location``, ...) or like a Python keyword becomes a keyword argument with a
trailing underscore (``timeout_``, ``from_``) that maps back to the proto
field. Keyword RPC and service names get the same underscore (``import_``).
Names that would still shadow one another stop generation with SystemExit.

Generated methods never import grpc: they call ``Caller.invoke`` from
``clappform._runtime``, which the transport (or a test double) implements.

The generator has no per-service configuration. It keys only on the two
commons pagination message names, a family-alias map and a small acronym
table for snake_case.
"""

from __future__ import annotations

import keyword
import re
import textwrap
from collections import Counter
from pathlib import Path
from typing import Any

from google.protobuf import descriptor, descriptor_pb2, descriptor_pool, message_factory

FAMILY_ALIASES = {"authoriser": "auth"}
# Parameter names every generated method already uses for itself.
RESERVED_PARAMS = frozenset({"self", "request", "requests", "timeout", "metadata", "location"})
# Family attributes that clappform._client attaches by hand.
RESERVED_ATTRS = {"data": frozenset({"collection", "query"})}
# Module-level names of a generated module that a service class must not shadow.
MODULE_NAMES = frozenset({"Any", "Iterable", "Iterator", "Mapping", "Sequence"})
PAGINATION_REQUEST = ".clappform.v1.commons.PaginationRequest"
PAGINATION_MESSAGE = ".clappform.v1.commons.Pagination"
PB2_IMPORT_PREFIX = "clappform.gen."
OPENAPI_OPERATION = "grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation"

# CamelCase words the snake_case regexes split in the wrong place, mapped to
# a spelling that splits right: OAuth -> oauth rather than o_auth.
ACRONYMS = {"OAuth": "Oauth", "SAML": "Saml", "WhatsApp": "Whatsapp"}

HEADER = '"""Generated by tools/generate.py. Do not edit."""\n'

_F = descriptor_pb2.FieldDescriptorProto
_SCALAR_TYPES: dict[int, str] = {
    _F.TYPE_DOUBLE: "float",
    _F.TYPE_FLOAT: "float",
    _F.TYPE_INT64: "int",
    _F.TYPE_UINT64: "int",
    _F.TYPE_INT32: "int",
    _F.TYPE_FIXED64: "int",
    _F.TYPE_FIXED32: "int",
    _F.TYPE_BOOL: "bool",
    _F.TYPE_STRING: "str",
    _F.TYPE_GROUP: "Any",
    _F.TYPE_BYTES: "bytes",
    _F.TYPE_UINT32: "int",
    _F.TYPE_SFIXED32: "int",
    _F.TYPE_SFIXED64: "int",
    _F.TYPE_SINT32: "int",
    _F.TYPE_SINT64: "int",
}

# Source-info path components: field numbers in descriptor.proto.
_FILE_MESSAGE, _FILE_SERVICE = 4, 6
_MESSAGE_FIELD, _MESSAGE_NESTED = 2, 3
_SERVICE_METHOD = 2

SourcePath = tuple[int, ...]


def snake_case(name: str) -> str:
    for word, replacement in ACRONYMS.items():
        name = name.replace(word, replacement)
    s = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", name)
    return re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s).lower()


def py_name(name: str) -> str:
    """Append ``_`` to a Python keyword so it can serve as an identifier."""
    return f"{name}_" if keyword.iskeyword(name) else name


def param_name(field_name: str) -> str:
    """Keyword-argument name for a request field."""
    if field_name in RESERVED_PARAMS:
        return f"{field_name}_"
    return py_name(field_name)


def _camel(name: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in name.split("_"))


def _pb2_module(proto_path: str) -> str:
    """clappform/data/v1/insert/insert.proto -> clappform.gen....insert_pb2"""
    dotted = proto_path[: -len(".proto")].replace("/", ".")
    if proto_path.startswith("google/protobuf/"):
        return f"{dotted}_pb2"  # well-known types ship with the protobuf runtime
    return f"{PB2_IMPORT_PREFIX}{dotted}_pb2"


def _pb2_alias(proto_path: str) -> str:
    return "_m_" + re.sub(r"\W", "_", proto_path[: -len(".proto")])


def _clean_comment(text: str) -> str:
    """Dedent a proto comment and make it safe inside a docstring."""
    text = textwrap.dedent(text).strip()
    return text.replace("\\", "\\\\").replace('"""', "'''")


class _OperationDocs:
    """Reads the grpc-gateway ``openapiv2_operation`` option off a method.

    ``descriptor_pb2`` keeps an extension as unknown bytes. Loading the
    descriptor set into its own pool registers the extension, so the method
    options re-parse into a message that exposes it.
    """

    def __init__(self, fds: descriptor_pb2.FileDescriptorSet) -> None:
        self._extension: descriptor.FieldDescriptor | None = None
        self._options_cls: Any = None
        names = [file.name for file in fds.file]
        if "google/protobuf/descriptor.proto" not in names:
            return
        pool = descriptor_pool.DescriptorPool()
        for file in fds.file:
            pool.Add(file)
        try:
            self._extension = pool.FindExtensionByName(OPENAPI_OPERATION)
        except KeyError:
            return
        classes = message_factory.GetMessageClassesForFiles(names, pool)
        self._options_cls = classes["google.protobuf.MethodOptions"]

    def doc(self, method: descriptor_pb2.MethodDescriptorProto) -> str:
        if self._extension is None:
            return ""
        options = self._options_cls.FromString(method.options.SerializeToString())
        if not options.HasExtension(self._extension):
            return ""
        operation = options.Extensions[self._extension]
        parts = (_clean_comment(operation.summary), _clean_comment(operation.description))
        return "\n\n".join(part for part in parts if part)


class _Index:
    """Message, enum, comment and option lookups across the descriptor set.

    ``used`` collects the file of every type the emitted code references, so
    a module's imports always cover its annotations.
    """

    def __init__(self, fds: descriptor_pb2.FileDescriptorSet) -> None:
        self.files = list(fds.file)
        # ".pkg.Msg[.Nested]" -> (message descriptor, owning file, source path)
        self.messages: dict[
            str,
            tuple[
                descriptor_pb2.DescriptorProto,
                descriptor_pb2.FileDescriptorProto,
                SourcePath,
            ],
        ] = {}
        # ".pkg[.Msg].Enum" -> owning file
        self.enums: dict[str, descriptor_pb2.FileDescriptorProto] = {}
        # file name -> source path -> cleaned leading + trailing comment
        self.comments: dict[str, dict[SourcePath, str]] = {}
        self.used: set[str] = set()
        for file in self.files:
            prefix = f".{file.package}" if file.package else ""
            for i, message in enumerate(file.message_type):
                self._register(message, prefix, file, (_FILE_MESSAGE, i))
            for enum in file.enum_type:
                self.enums[f"{prefix}.{enum.name}"] = file
            self.comments[file.name] = {
                tuple(loc.path): _clean_comment(
                    "\n".join(c for c in (loc.leading_comments, loc.trailing_comments) if c)
                )
                for loc in file.source_code_info.location
                if loc.leading_comments or loc.trailing_comments
            }
        self.operations = _OperationDocs(fds)

    def _register(
        self,
        message: descriptor_pb2.DescriptorProto,
        prefix: str,
        file: descriptor_pb2.FileDescriptorProto,
        path: SourcePath,
    ) -> None:
        full = f"{prefix}.{message.name}"
        self.messages[full] = (message, file, path)
        for i, nested in enumerate(message.nested_type):
            self._register(nested, full, file, (*path, _MESSAGE_NESTED, i))
        for enum in message.enum_type:
            self.enums[f"{full}.{enum.name}"] = file

    def message(self, type_name: str) -> descriptor_pb2.DescriptorProto:
        return self.messages[type_name][0]

    def _ref(self, type_name: str, file: descriptor_pb2.FileDescriptorProto) -> str:
        self.used.add(file.name)
        package_prefix = f".{file.package}." if file.package else "."
        return f"{_pb2_alias(file.name)}.{type_name[len(package_prefix):]}"

    def class_ref(self, type_name: str) -> str:
        """Python reference for a message type, via its pb2 module alias."""
        return self._ref(type_name, self.messages[type_name][1])

    def enum_ref(self, type_name: str) -> str:
        """Python reference for an enum type, via its pb2 module alias."""
        return self._ref(type_name, self.enums[type_name])

    def comment(self, file: descriptor_pb2.FileDescriptorProto, path: SourcePath) -> str:
        return self.comments[file.name].get(path, "")

    def field_comments(self, type_name: str) -> dict[str, str]:
        message, file, path = self.messages[type_name]
        return {
            field.name: self.comment(file, (*path, _MESSAGE_FIELD, i))
            for i, field in enumerate(message.field)
        }


def _annotation(field: descriptor_pb2.FieldDescriptorProto, index: _Index) -> str:
    """Type hint for a request field, matching what the message constructor takes."""
    if field.type == _F.TYPE_MESSAGE:
        entry = index.message(field.type_name)
        if entry.options.map_entry:
            key = _annotation(entry.field[0], index)
            value = _annotation(entry.field[1], index)
            return f"dict[{key}, {value}]"
        base = f"{index.class_ref(field.type_name)} | Mapping[str, Any]"
    elif field.type == _F.TYPE_ENUM:
        # The pb2 stubs declare an enum as an int subclass, and the
        # constructor also takes a value's name.
        base = f"{index.enum_ref(field.type_name)} | int | str"
    else:
        base = _SCALAR_TYPES.get(field.type, "Any")
    if field.label == _F.LABEL_REPEATED:
        return f"Sequence[{base}]"
    return base


def _split_summary(lines: list[str]) -> tuple[str, list[str]]:
    """Return (first sentence on one line, the lines after it)."""
    for i, line in enumerate(lines):
        match = re.search(r"[.!?](\s+|$)", line)
        if match:
            head = [*lines[:i], line[: match.start() + 1]]
            tail = line[match.end():].strip()
            after = [tail, *lines[i + 1:]] if tail else lines[i + 1:]
            return " ".join(part.strip() for part in head), after
    return " ".join(line.strip() for line in lines), []


def _docstring_head(text: str) -> list[str]:
    """Lay out a comment as a one-line summary, a blank line, then the rest.

    When the first paragraph wraps over several lines, its first sentence
    becomes the summary and the remaining lines follow unchanged.
    """
    paragraphs = re.split(r"\n\s*\n", text)
    first = paragraphs[0].splitlines()
    lines = first[:1]
    rest = first[1:]
    if rest:
        summary, rest = _split_summary(first)
        lines = [summary]
    if rest:
        lines += ["", *rest]
    for paragraph in paragraphs[1:]:
        lines += ["", *paragraph.splitlines()]
    return lines


def _args_block(
    fields: list[descriptor_pb2.FieldDescriptorProto], docs: dict[str, str]
) -> list[str]:
    entries = [(param_name(f.name), docs.get(f.name, "")) for f in fields]
    entries = [(name, doc) for name, doc in entries if doc]
    if not entries:
        return []
    out = ["", "Args:"]
    for name, doc in entries:
        first, *rest = doc.splitlines()
        out.append(f"    {name}: {first}")
        out.extend(f"        {line}" for line in rest)
    return out


class _MethodPlan:
    def __init__(
        self,
        file: descriptor_pb2.FileDescriptorProto,
        service_idx: int,
        method_idx: int,
        method: descriptor_pb2.MethodDescriptorProto,
        index: _Index,
    ) -> None:
        self.method = method
        self.name = py_name(snake_case(method.name))
        self.comment = index.comment(
            file, (_FILE_SERVICE, service_idx, _SERVICE_METHOD, method_idx)
        ) or index.operations.doc(method)
        self.input_type = method.input_type
        self.output_type = method.output_type
        self.client_streaming = method.client_streaming
        self.server_streaming = method.server_streaming
        self.kind = (
            f"{'stream' if method.client_streaming else 'unary'}_"
            f"{'stream' if method.server_streaming else 'unary'}"
        )
        self.full_method = f"/{file.package}.{file.service[service_idx].name}/{method.name}"

        self.flattened: list[descriptor_pb2.FieldDescriptorProto] = []
        self.field_docs: dict[str, str] = {}
        if not method.client_streaming:
            self.flattened = list(index.message(method.input_type).field)
            self.field_docs = index.field_comments(method.input_type)
            counts = Counter(param_name(f.name) for f in self.flattened)
            clashes = sorted(name for name, n in counts.items() if n > 1)
            if clashes:
                raise SystemExit(
                    f"servicegen: {self.full_method}: request fields map to the same "
                    f"keyword argument: {', '.join(clashes)}"
                )

        self.pagination = self._pagination_plan(index)

    def _pagination_plan(self, index: _Index) -> tuple[str, str, str, list[str]] | None:
        """(pagination_field, items_field, item_type_ref, other repeated) or None."""
        if self.client_streaming or self.server_streaming:
            return None
        if self.input_type != PAGINATION_REQUEST:
            return None
        output = index.message(self.output_type)
        pagination_field = next(
            (
                f.name
                for f in output.field
                if f.type == _F.TYPE_MESSAGE and f.type_name == PAGINATION_MESSAGE
            ),
            None,
        )
        if pagination_field is None:
            return None
        repeated = [
            f
            for f in output.field
            if f.label == _F.LABEL_REPEATED
            and f.type == _F.TYPE_MESSAGE
            and not index.message(f.type_name).options.map_entry
        ]
        if not repeated:
            return None
        items, others = repeated[0], [f.name for f in repeated[1:]]
        return pagination_field, items.name, index.class_ref(items.type_name), others


def _call_options(out: list[str]) -> None:
    out.append("        timeout: float | None = None,")
    out.append("        metadata: tuple[tuple[str, str], ...] | None = None,")
    out.append("        location: str | None = None,")


def _invoke(plan: _MethodPlan, request_var: str, request_ref: str, response_ref: str) -> list[str]:
    return [
        "        return self._caller.invoke(",
        f'            "{plan.kind}",',
        f'            "{plan.full_method}",',
        f"            {request_var},",
        f"            {request_ref},",
        f"            {response_ref},",
        "            timeout=timeout,",
        "            metadata=metadata,",
        "            location=location,",
        "        )",
        "",
    ]


def _emit_method(plan: _MethodPlan, index: _Index, out: list[str]) -> None:
    request_ref = index.class_ref(plan.input_type)
    response_ref = index.class_ref(plan.output_type)
    return_ann = f"Iterator[{response_ref}]" if plan.server_streaming else response_ref

    doc_lines = _docstring_head(plan.comment) if plan.comment else []
    if doc_lines:
        doc_lines.append("")
    doc_lines.append(f"RPC: {plan.full_method} ({plan.kind.replace('_', '-')})")
    doc_lines += _args_block(plan.flattened, plan.field_docs)

    if plan.client_streaming:
        out.append(f"    def {plan.name}(")
        out.append("        self,")
        out.append(f"        requests: Iterable[{request_ref}],")
        out.append("        *,")
        _call_options(out)
        out.append(f"    ) -> {return_ann}:")
        _emit_docstring(doc_lines, out)
        out.append(
            f"        _requests = _runtime.ensure_iterable(requests, {request_ref})"
        )
        out.extend(_invoke(plan, "_requests", request_ref, response_ref))
        return

    out.append(f"    def {plan.name}(")
    out.append("        self,")
    out.append(f"        request: {request_ref} | None = None,")
    out.append("        *,")
    for field in plan.flattened:
        out.append(
            f"        {param_name(field.name)}: {_annotation(field, index)} | None = None,"
        )
    _call_options(out)
    out.append(f"    ) -> {return_ann}:")
    _emit_docstring(doc_lines, out)
    if plan.flattened:
        pairs = ", ".join(f'("{f.name}", {param_name(f.name)})' for f in plan.flattened)
        out.append(
            f"        _provided = {{_k: _v for _k, _v in ({pairs},) if _v is not None}}"
        )
    else:
        out.append("        _provided: dict[str, Any] = {}")
    out.append(
        f"        _request = _runtime.build_request({request_ref}, request, _provided)"
    )
    out.extend(_invoke(plan, "_request", request_ref, response_ref))

    if plan.pagination is not None:
        _emit_pagination(plan, index, out)


def _emit_pagination(plan: _MethodPlan, index: _Index, out: list[str]) -> None:
    # Narrowing for mypy: callers only reach this for a plan with pagination.
    assert plan.pagination is not None  # noqa: S101
    pagination_field, items_field, item_ref, others = plan.pagination
    fields = [f for f in plan.flattened if f.name != "page"]
    out.append(f"    def iter_{plan.name}(")
    out.append("        self,")
    out.append("        *,")
    for field in fields:
        out.append(
            f"        {param_name(field.name)}: {_annotation(field, index)} | None = None,"
        )
    _call_options(out)
    out.append(f"    ) -> Iterator[{item_ref}]:")
    doc = [
        f"Auto-paginating variant of ``{plan.name}``.",
        "",
        f"Yields each item from ``{items_field}``, requesting page 1, 2, ... until",
        f"a page comes back empty or ``{pagination_field}.pages`` is reached.",
    ]
    if others:
        listed = ", ".join(f"``{name}``" for name in others)
        doc.append(
            f"Only ``{items_field}`` is yielded; call ``{plan.name}`` for {listed}."
        )
    doc += _args_block(fields, plan.field_docs)
    _emit_docstring(doc, out)
    out.append("        _page = 1")
    out.append("        while True:")
    args = ["page=_page"]
    args += [f"{param_name(f.name)}={param_name(f.name)}" for f in fields]
    args += ["timeout=timeout", "metadata=metadata", "location=location"]
    out.append(f"            _resp = self.{plan.name}({', '.join(args)})")
    out.append(f"            _items = _resp.{items_field}")
    out.append("            yield from _items")
    out.append(f"            if not _items or _resp.{pagination_field}.pages <= _page:")
    out.append("                break")
    out.append("            _page += 1")
    out.append("")


def _emit_docstring(lines: list[str], out: list[str]) -> None:
    if len(lines) == 1:
        out.append(f'        """{lines[0]}"""')
        return
    out.append('        """' + lines[0])
    out.extend(f"        {line}".rstrip() for line in lines[1:])
    out.append('        """')


def _family_of(package: str) -> str | None:
    parts = package.split(".")
    if len(parts) < 3 or parts[0] != "clappform":
        return None
    if parts[1].startswith("v") and parts[1][1:].isdigit():
        return None  # clappform.v1.commons: shared types, no services
    return parts[1]


def _family_class(alias: str) -> str:
    return f"{_camel(alias)}API"


def _check_unique(kind: str, family: str, names: list[str]) -> None:
    duplicates = sorted(name for name, n in Counter(names).items() if n > 1)
    if duplicates:
        raise SystemExit(
            f"servicegen: {family} family: several services generate the {kind} "
            f"{', '.join(duplicates)}"
        )


_ServiceEntry = tuple[
    descriptor_pb2.FileDescriptorProto, int, descriptor_pb2.ServiceDescriptorProto
]


def _service_names(
    alias: str, entries: list[_ServiceEntry]
) -> list[tuple[str, str]]:
    """Return (class name, family attribute) per service, in entry order.

    A name that several services in the family share is suffixed with the
    package's last component on every one of them, so the result does not
    depend on which proto file sorts first.
    """
    def base_attr(service: descriptor_pb2.ServiceDescriptorProto) -> str:
        return snake_case(service.name.removesuffix("Management") or service.name)

    class_counts = Counter(service.name for _, _, service in entries)
    attr_counts = Counter(base_attr(service) for _, _, service in entries)
    names = []
    for file, _, service in entries:
        suffix = file.package.rsplit(".", 1)[-1]
        class_name = service.name
        if class_counts[class_name] > 1:
            class_name += _camel(suffix)
        attr = base_attr(service)
        if attr_counts[attr] > 1:
            attr = f"{attr}_{suffix}"
        names.append((py_name(class_name), py_name(attr)))

    classes = [class_name for class_name, _ in names]
    _check_unique("class", alias, [*classes, _family_class(alias)])
    shadowing = sorted(MODULE_NAMES.intersection(classes))
    if shadowing:
        raise SystemExit(f"servicegen: {alias} family: class shadows an import: {shadowing}")
    attrs = [attr for _, attr in names]
    _check_unique("attribute", alias, attrs)
    reserved = sorted(RESERVED_ATTRS.get(alias, frozenset()).intersection(attrs))
    if reserved:
        raise SystemExit(
            f"servicegen: {alias} family: attribute {', '.join(reserved)} is reserved "
            "for the hand-written accessor in clappform._client"
        )
    return names


def _render_service(
    file: descriptor_pb2.FileDescriptorProto,
    service_idx: int,
    service: descriptor_pb2.ServiceDescriptorProto,
    class_name: str,
    index: _Index,
) -> str:
    """Return the wrapper class source for one service."""
    plans = [
        _MethodPlan(file, service_idx, method_idx, method, index)
        for method_idx, method in enumerate(service.method)
    ]
    methods = [plan.name for plan in plans]
    methods += [f"iter_{plan.name}" for plan in plans if plan.pagination is not None]
    duplicates = sorted(name for name, n in Counter(methods).items() if n > 1)
    if duplicates:
        raise SystemExit(
            f"servicegen: {file.package}.{service.name}: several RPCs generate the "
            f"method {', '.join(duplicates)}"
        )

    out: list[str] = []
    out.append(f"class {class_name}(_runtime.ServiceBase):")
    out.append(f'    """Wrapper for {file.package}.{service.name}."""')
    out.append("")
    for plan in plans:
        _emit_method(plan, index, out)
    return "\n".join(out).rstrip() + "\n"


def _render_family(
    family: str,
    files: list[descriptor_pb2.FileDescriptorProto],
    index: _Index,
) -> tuple[str, str, str]:
    """Return (module alias, family class name, module source) for one family."""
    alias = FAMILY_ALIASES.get(family, family)
    class_name = _family_class(alias)

    entries = [
        (file, service_idx, service)
        for file in sorted(files, key=lambda f: f.name)
        for service_idx, service in enumerate(file.service)
    ]
    names = _service_names(alias, entries)

    index.used = set()
    service_blocks = [
        _render_service(file, service_idx, service, service_class, index)
        for (file, service_idx, service), (service_class, _) in zip(entries, names, strict=True)
    ]

    module_lines = [HEADER]
    module_lines.append("from __future__ import annotations")
    module_lines.append("")
    module_lines.append("from collections.abc import Iterable, Iterator, Mapping, Sequence")
    module_lines.append("from typing import Any")
    module_lines.append("")
    module_lines.append("from clappform import _runtime")
    for path in sorted(index.used):
        module_lines.append(f"import {_pb2_module(path)} as {_pb2_alias(path)}")
    module_lines.append("")
    module_lines.append("")
    for block in service_blocks:
        module_lines.append(block)
        module_lines.append("")
    module_lines.append(f"class {class_name}:")
    module_lines.append(f'    """Generated sub-client for the {family} API."""')
    module_lines.append("")
    module_lines.append("    def __init__(self, caller: _runtime.Caller) -> None:")
    for service_class, attr in names:
        module_lines.append(f"        self.{attr} = {service_class}(caller)")
    module_lines.append("")
    return alias, class_name, "\n".join(module_lines)


def _render_init(registry: list[tuple[str, str, str]]) -> str:
    """Return the services package __init__, given (alias, class, module) rows."""
    init_lines = [HEADER]
    init_lines.append("from __future__ import annotations")
    init_lines.append("")
    for _alias, class_name, module in registry:
        init_lines.append(f"from clappform.services.{module} import {class_name}")
    init_lines.append("")
    init_lines.append("API_FAMILIES: dict[str, type] = {")
    for alias, class_name, _module in registry:
        init_lines.append(f'    "{alias}": {class_name},')
    init_lines.append("}")
    init_lines.append("")
    init_lines.append(
        "__all__ = [\"API_FAMILIES\", "
        + ", ".join(f'"{class_name}"' for _a, class_name, _m in registry)
        + "]"
    )
    init_lines.append("")
    return "\n".join(init_lines)


def generate_sources(descriptor_set: bytes) -> dict[str, str]:
    """Return {module filename: source} for the full service layer."""
    fds = descriptor_pb2.FileDescriptorSet()
    fds.MergeFromString(descriptor_set)
    index = _Index(fds)

    families: dict[str, list[descriptor_pb2.FileDescriptorProto]] = {}
    for file in fds.file:
        family = _family_of(file.package)
        if family is not None and file.service:
            families.setdefault(family, []).append(file)

    sources: dict[str, str] = {}
    registry: list[tuple[str, str, str]] = []  # (attr, class, module)
    for family in sorted(families):
        alias, class_name, source = _render_family(family, families[family], index)
        sources[f"{alias}.py"] = source
        registry.append((alias, class_name, alias))

    sources["__init__.py"] = _render_init(registry)
    return sources


def generate(descriptor_set: bytes, out_dir: Path) -> None:
    sources = generate_sources(descriptor_set)
    if out_dir.exists():
        for existing in out_dir.glob("*.py"):
            existing.unlink()
    out_dir.mkdir(parents=True, exist_ok=True)
    for filename, source in sources.items():
        (out_dir / filename).write_text(source, encoding="utf-8", newline="\n")
